### ISSUE TITLE
Layout for a single/individual page

### ISSUE THREAD

**Issue by bd0bd** [backdrop/backdrop-issues#1126]
Hi!

I have read the instructions - https://backdropcms.org/guide/layouts - how to make a custom layout for a single/individual page but it is not enough clear for me how to do it (the logic is different from what I have had for 15 years). May be somebody could give me exact instructions how to do it? :)

For all the pages I have the Default Layout with **2 columns**.
For example I need to make **1 column** layout for **About Us** page - http://domain.com/about - and for **Books** page - http://domain.com/books. These pages - About Us and Books - are created like Basic page type. How to do it they have a 1 column layout?

In the CMS I use for 5 years - it is very simple to do. In any page configuration I can select the layout/template type exactly for this page. It is the same like in Backdrop's page configuration I can select a parent item in the Menu settings.

Thank you!

**UPDATE**
Sorry, I was wrong - the **Books** page (books) is not Basic page type, it is Views page.

**Comment by Graham-72** [comment]
If you go to administration>structure>layouts and choose add layout do you not have the option of a single column layout as one of the settings? I use this to specify a 1 column layout specific for certain pages on my site. If you need more information I will gladly write more.

**Comment by bd0bd** [comment]
Hi Graham! Thank you!
Sure, I have all these things. But I do not understand how to apply 1 column layout for certain pages. May be it sounds a little bit stupid but it is :)
There is **Path** required field and I do not understand why?
But if I type **about** (my About Us page URL) in this field then I get this warning:

*That path is currently assigned to be an alias for "node/2". Delete the alias first, then save this layout.*

So I am confused and messed up.

Thank you!

**Comment by Graham-72** [comment]
I will try and explain what I have been doing. Like you I am not sure what exactly the path field is for and I rather assume it defines the pattern of URL that the layout will apply to, not the exact URL. I am sure someone else will now clarify this for us.

What I do to apply a layout to a particular page is to add a condition to the layout using 'add condition' at the bottom of the layout settings page, then select the condition 'URL path', add this, then in the following form specify the path for this page as node/N. (I am using the node number here as revealed when going to edit it, but perhaps the name will work just as well)

There is a similar procedure when adding blocks to the different regions in the layout, whereby you can add conditions so that a particular block is only included on specified pages, rather than all pages using that layout.

So I have ended with three or four layouts in use on a simple site, one for the home page, one default one used for the majority of pages, and one or two specialised ones where perhaps a different column layout is needed.

I hope this helps - questions welcomed, though I don't know all the answers.

**Comment by bd0bd** [comment]
Thank you! Yes, I understand the 'add condition' option - there is no questions about this. But the path field is a required one and I do not understand how to overcome this obstacle.

**Comment by Graham-72** [comment]
OK. I put node/% because that is the pattern of the URL for my pages.

**Comment by bd0bd** [comment]
**Graham-72**, thank you very much for your help!
The issue is solved.
Everything is working well now.
I have simply put **node/%** in the path field.

**Comment by Graham-72** [comment]
I am glad to have helped. It is a powerful system and I still have a lot to learn, but suggestions from others are always a great help.

**Comment by bd0bd** [comment]
Hm, my 1 column layout is working for Contact page (contact) but it does not apply for Books page (books) - it is still has 2 column layout. 

The Contact page is a regular Basic page type and Books page is done via a Views.

![layout](https://cloud.githubusercontent.com/assets/13515302/9557065/a554d74a-4de1-11e5-898f-d4a5a015ddda.gif)

**Comment by bd0bd** [comment]
Also I try condition "Node: Type" but it does not work too.

![node_type](https://cloud.githubusercontent.com/assets/13515302/9557660/68eea484-4de6-11e5-8c54-1f08e449bccc.gif)

**Comment by bd0bd** [comment]
Well, the issue was solved by filling the Path with **books**.
But here is a question - why I can fill in **books** but it is not allowed to fill in **about** in the Path?
It is like a nonsense for me :)

**Comment by quicksketch** [comment]
>  But here is a question - why I can fill in books but it is not allowed to fill in about in the Path?

This explanation is here with a deeper understanding of aliases vs. paths. You mentioned:

> The Contact page is a regular Basic page type and Books page is done via Views.

So as you've said here, the "books" path is created through Views, so it's a "real" system path. The contact page has the system path "node/%", but is merely aliased at "about". In order for Layouts to affect a page, they need to respond based the system path.

Architecturally, this is all deeply rooted in the Backdrop/Drupal menu/routing system. Unfortunately, I can see all too easily how confusing this is when creating layouts. There are things we could do to paper-over these problems, but I'm afraid of what complexity/confusion could result from it. For example, instead of giving the error *That path is currently assigned to be an alias for "node/2". Delete the alias first, then save this layout.*, we could instead make the changes for the user, automatically adjusting the settings internally to match what users probably wanted (e.g. looking up the alias, changing the path to the system path, then adding a path condition based on the alias value).

**Comment by quicksketch** [comment]
Also @bd0bd, thanks for trying out Backdrop and welcome to the community! :smile:

**Comment by biolithic** [comment]
Thanks for jumping in @quicksketch.  It seems like there are things that
"Drupal people just know", such as paths and aliases.  For example, "I
don't know what I don't know about being a beginner".
I hope people like @bd0bd stick around while we learn what we don't know
yet.

Thanks @bd0bd !

**Comment by klonos** [comment]
You mean that the way we have it currently conditions work with system paths but not with aliases?

> ...automatically adjusting the settings internally to match what users probably wanted (e.g. looking up the alias, changing the path to the system path, then adding a path condition based on the alias value).

Wouldn't it be easier (not to mention *a lot* better UX-wise) to permit path aliases since that seems to be how people expect this to work? ...we should be doing the alias-to-path translation "transparently" in the background and the list should still show whatever the user entered there (alias or system path). Ideally, I would like to see system paths (```node/x```) eliminated -entirely if possible- from the UI (https://github.com/backdrop/backdrop-issues/issues/899#issuecomment-106857163 and also #940). They should still be there for all us *geeks*, but end users need not know anything about them.

Also, another thought: how about instead of going to the layouts admin UI and messing with visibility conditions for assigning a specific layout to a page (or a set of pages for that matter), wouldn't it be better to allow selecting a page layout from the content type edit form or view edit form instead? ...similarly to what we plan for #899.

**Comment by bd0bd** [comment]
**quicksketch**, **biolithic**, thank you!

**Comment by bd0bd** [comment]
Hi!

I have views page "Book" and it has 1 column layout with Path: books.
I would like this layout to work for all other pages in this path, i.e. - books/design-everyday-things-revised/, books/mobile-usability/, books/living-with-complexity/ etc.
I got confused.
Please, advise how to make it?
Thank you!

**Comment by quicksketch** [comment]
Hi there @bd0bd! It depends on how these other paths are set up. 

> i.e. - books/design-everyday-things-revised/, books/mobile-usability/, books/living-with-complexity/ etc.

Are these paths nodes? Or are they contextual filters (arguments) passed into your view at `/books`?

Backdrop doesn't have the ability to match a layout to a full wildcard path, because you could easily end up with multiple layouts attempting to match the same path. While that may be confusing, the primary reason for not matching all wildcards is for performance, figuring out which layout would handle the path on first load would be expensive.

So, to answer your question. If you want to make all sub-paths match as well, you have to clone the current layout, then set the new path for the sub-pages. You can clone any layout from the list of all layouts under the drop button.

![selection_002](https://cloud.githubusercontent.com/assets/100206/9833549/ba3ac45e-5957-11e5-9b4d-cc4d71f691d7.png)

If the sub-pages are nodes, then enter the path `node/%`, and add a condition to the entire layout to only apply to nodes that are of the "Book" content type.

If the sub-pages are a view that takes an argument, then enter the path `books/%`.

**Comment by bd0bd** [comment]
Hi ***quicksketch *! Thank you very much for your help!

Finally I was able to solve the issues with your help.
But in my mind it is a little bit complicated system for a newcomer (the need to clone the layout).
I do not offer any solution, it is just my point of view/

![layout_1](https://cloud.githubusercontent.com/assets/13515302/9836167/ab14a060-5a17-11e5-9ef4-33a2538db7ab.gif)

![layout_2](https://cloud.githubusercontent.com/assets/13515302/9836169/b1e1328c-5a17-11e5-843f-fbae8a197d04.gif)

**Comment by quicksketch** [comment]
:clap: Well done and great screenshots. Agreed that Layouts are a complex tool and could be difficult for newcomers to Backdrop (which is just about everyone at this point).

We've got a good number of followup issues for Layouts that hopefully should make things a bit easier. See the meta issue at #345.

**Comment by bd0bd** [comment]
**quicksketch**, thank you!
