### ISSUE TITLE
CKEditor toolbar: Cannot save the flag button ("Anchor") position in the toolbar.

### ISSUE THREAD

**Issue by Graham-72** [backdrop/backdrop-issues#1231]
Ref #1087 
I find I cannot save a change in a toolbar.
![full html - browsers bookshop 2015-09-20 12-07-41](https://cloud.githubusercontent.com/assets/10559274/9980579/0b780800-5f97-11e5-9a5f-bccd74e4abde.png)

---
PR from @jenlampton at https://github.com/backdrop/backdrop/pull/1552

**Comment by quicksketch** [comment]
Thanks @Graham-72. I was able to reproduce the issue described here. It looks like only this flag button ("Anchor") exhibits the problem that it cannot be saved. Is that what you are experiencing as well?

**Comment by Graham-72** [comment]
Yes, confirmed. I have just done a test by trying to move all the buttons and only the flag button refused to stay in its new position. So it is a minor issue.

**Comment by Graham-72** [comment]
Should this be added to meta issue #1087 ?

**Comment by klonos** [comment]
I would say so.

**Comment by gifad** [comment]
My comment at #1542 was wrong : the anchor buttons shows on my test site, but it is using a "free" custom build (v4.5.5) from CKSource (I need the 4.5 drag&drop API).
It's worth noting that firebug shows the "link" button as 
`<span style="background-image:url('/backdrop/core/modules/ckeditor/js/plugins/backdroplink//link.png?t=FACH');background-position:0 undefinedpx;background-size:16px;" class="cke_button_icon cke_button__backdroplink_icon">&nbsp;</span>` 
whereas "my" "anchor" button shows as : 
`<span style="background-image:url('http://p1347.phpnet.org/backdrop/core/misc/ckeditor/plugins/icons.png?t=FACH');background-position:0 -1296px;background-size:auto;" class="cke_button_icon cke_button__anchor_icon">&nbsp;</span>`
Note in the "link" button : 
- the incorrect backgroud-image url with duplicate "/"
- the incorrect background-position

You can see it live at http://p1347.phpnet.org/backdrop/l/3rgz8UIEd0Vd/node/24/edit and note the original CKEditor buttons are colored, while the backdrop specific buttons are monochrome.
 This lets me think that the problem is in the hacked CKEditor supplied with backdrop - note the interesting comment in `backdrop/core/misc/ckeditor/build-config.js` : 
```
/**
 * This is a Drupal-optimized build of CKEditor.
 *
```
Is backdrop stuck with the 4.4 version of the "image2" plugin ?

**Comment by gifad** [comment]
Wrong again !
As usual, when you have a problem with backdrop, remember that **Backdrop is Drupal 8**, not Drupal 7 !!!
Visit a drupal 8 site, you will find no anchor button : The anchor functionality is part of the link plugin, which has been removed from the "drupal 8 optimized" library, and replaced by a Drupallink plugin, which does not even know what an anchor is...
So download a regular CKEditor build, or make your own with CKBuilder, and your anchor button will be back.

**Comment by Graham-72** [comment]
@klonos Please can this be added to [META] CKEditor/Rich text editor followups #1087 ?

**Comment by klonos** [comment]
Done :wink:

**Comment by gifad** [comment]
I just found the reason of the original question : The filter module consider that the "id" attribute is invalid for an "a" tag. I could not find the exact location where those rules are defined - this is odd, because id is allowed for a link, while name is not (in HTML5).

Anyway, removing the 'id' attribute in the "Anchor" definution array solves this problem.

which is pretty useless, as there is currently no plugin to handle anchors, as I stated above...

**Comment by jenlampton** [comment]
This is still an issue on 1.5.x-dev, even after the recent update of the CKEditor to 4.5.x

**Comment by jenlampton** [comment]
Since I don't like this bug being in Backdrop, the easiest solution is to remove the feature that does not work. *cries* Longer term, we will need to add our own version of the Anchor plugin that is not part of the link plugin.  Likely as a part of  #1777.

**Comment by quicksketch** [comment]
Yeah... a sad conclusion but I think you're right @jenlampton. This button doesn't do anything because there is no code backing it up. Adding anchor tag support is not trivial so we should remove the broken button from the UI. I've merged https://github.com/backdrop/backdrop/issues/1552 into 1.x and 1.4.x.

I'm not sure if this is part of the Advanced Link functionality in #1777 or not. I know it's bitter to close an issue when the underlying request (fix the anchor button) hasn't been resolved. But let's close this "bug" and open a new feature request, either as part of #1777 or a new one entirely.
