### ISSUE TITLE
[UX] upload an CMI config.tar.gz automatically re: #1199

### ISSUE THREAD

**Issue by serundeputy** [backdrop/backdrop-issues#1654]
Just like in #1199 on `/admin/config/development/configuration/full` if you choose your `config.tar.gz` file and don't/forget to hit upload before you click `Stage Import` you get nada.

No, feedback, nothing.

I think if it is possible like the images in #1199 that this should be auto uploaded once chosen.

**Comment by quicksketch** [comment]
Huh, strange. Well #1199 applies to this too, files everywhere are now auto-uploaded upon selection. I tried it out in 1.x and it worked great there. So unless it isn't working in 1.x currently for you, I believe this is already fixed and will be in 1.3.3.

**Comment by serundeputy** [comment]
still getting this on `1.x` (24 March 2016)

![screen shot 2016-03-24 at 6 53 40 pm](https://cloud.githubusercontent.com/assets/6763671/14033577/d4559264-f1f1-11e5-8dce-6f55f20dd213.png)
