### ISSUE TITLE
[UX] Allow non-reusable custom blocks created in Layouts to have an admin label

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#1703]
As per issue title. According to @jenlampton in #1522 and #1523, there must have been a field there available for setting an admin title. I don't see any such field any more. Regression perhaps?

---
PR by @klonos: https://github.com/backdrop/backdrop/pull/1729

**Comment by klonos** [comment]
The goal here is to be able to leave the block title empty (so that nothing is shown on the frontend), but have a custom block *admin UI* title that makes each block distinguish-able from the rest when editing a layout that has many custom blocks for example.

I would like to address that issue, but I don't know where to start. Any pointers?

**Comment by klonos** [comment]
...when I say I want to address the issue, mean start a PR that solves the issue in core.

I have a workaround already: enter in the block title field whatever is desirable for an admin label (in the layout admin UI) and then use CSS to hide it from the frontend.

This addresses the use case of needing an admin label for custom blocks while hiding it in the front end. If one needs a different title shown in the frontend than the one used as an admin title, then I guess they can use [the CSS content property](http://www.w3schools.com/cssref/pr_gen_content.asp).

These are only workarounds though and this should be resolved in core by having separate fields for admin label and frontend title.

**Comment by Dinornis** [comment]
@klonos This may have been fixed in 1.5.
The current `Add custom block` form includes an `Admin label` field and the `Display title` field is optional.

The `Add block "Custom block"` form available on the `Manage Block` pages in Layouts has an optional `Admin label` field available on the form when the `Make this block reusable` check box enabled.

**Comment by klonos** [comment]
Nope, still not fixed. To reproduce, add two custom blocks in any layout and leave their "Display title" field empty (that defines the title the block will have in the front-end). Notice how both blocks have "Custom block" as title *in the admin UI*.

**Comment by Dinornis** [comment]
Sorry, I was referring to the **_no way to customize that_** part of the title.

**Comment by jenlampton** [comment]
Maybe the problem only occurs for blocks that are not made reusable?

**Comment by Dinornis** [comment]
Yes, making the blocks reusable is sort of workaround.
Seems like adding a required `Admin label` field to the `Add block "Custom block"` form and removing the field that is hidden by the `Make this block reusable` option would be a good way to solve this?

**Comment by klonos** [comment]
> Maybe the problem only occurs for blocks that are not made reusable?

Yes, precisely. I think that we have the following options here:

1. Make the Admin label field *always* available no matter if the "Make this block reusable" option is checked or not (what @Dinornis has already suggested above). 

2. Set the block content as the block admin preview. This would mostly "automate" things compared to option 1 that would require the user to enter an admin label.

  I have cooked something like that already, screenshots upcoming...

**Comment by klonos** [comment]
Here's what a series of custom blocks would look like currently ...all in the "Bottom" region; none of them has a title (it falls back to "Custom block") and all of them have the same admin preview. No way to tell which is which:

![backdrop-issue1703-custom_blocks_with_no_titles](https://cloud.githubusercontent.com/assets/2423362/21756270/27816704-d673-11e6-80fc-0af372bfbff1.png)

**Comment by klonos** [comment]
...here's what it could look like with the block content rendered as their admin preview:

![backdrop-issue1703-custom_blocks_with_their_content_as_admin_preview](https://cloud.githubusercontent.com/assets/2423362/21756303/c0497328-d673-11e6-9d69-d07e98d711a4.png)

**Comment by klonos** [comment]
The first custom block has no title and no content. In such cases, the custom blocks are rendered as currently. You cannot tell them apart, but I see no reason why people would have more than one such "empty" custom block in their layouts. So edge case.

The 2nd one and all bu the 3rd one have content, but no title. See how easy it is to tell? 😉 

The 3rd one has a title, but no content. In such cases, the stock block type description is displayed as admin preview, but the block title is in the form of "Custom block: %block_title%".

**Comment by klonos** [comment]
...I wanted to post a few more screenshots of some thoughts and issues I've had, but since you reacted lightning-fast with a ❤️ @jenlampton, I'll go ahead and file a PR with what I have and then post those...

**Comment by klonos** [comment]
Alright, I have put an initial PR up for review. There's things to consider still...

1. What happens if the custom block has a really long text (especially when placed in a narrow region like a sidebar)? I have already tried trimming the content, passing it trough `backdrop_html_to_text` and also a combination of these, but I had no good results. (more on that as well as screenshots after I get some 💤 )

2. Do we want to make any other block types output their content as admin preview? I think not, but might be missing something.

3. Need to test how this PR works with custom blocks that are turned to reusable.

**Comment by Dinornis** [comment]
I like the idea of using the block content in the block preview on the layout page, but I think it should be optional.

I would like to have the `Admin label` field available on the `Add block "Custom block"` form even if not required. This would allow me to identify the custom blocks easier without the need to see their content.

**Comment by Dinornis** [comment]
The title and description of this issue is correctly identifying a problem of a missing `Admin label` for non-reusable Custom blocks.  The current PR is not addressing the problem of the unavailable Admin label, but rather adding a feature that makes the Block content visible on the `Manage Blocks` page.  That feature is being worked on in the https://github.com/backdrop/backdrop-issues/issues/2288 issue.
> As per issue title. According to @jenlampton in #1522 and #1523, there must have been a field there available for setting an admin title. I don't see any such field any more. Regression perhaps?

On the `Add block "Custom block"` form at _/admin/structure/layouts/manage/home/blocks_ form the `Admin label` field is only available to the user when they check the `Make this block reusable` box.

So perhaps this is a regression as the `Admin label` is available only for reusable blocks.

> I would like to address that issue, but I don't know where to start. Any pointers?

It seems to me that the best solution would be to make the `Admin label` available even if the Custom block is not reusable.

**Comment by Dinornis** [comment]
@klonos Perhaps something like `[UX] Make Admin Label available also for not reusable Custom Blocks` would be a better title for this issue?

**Comment by BWPanda** [comment]
It looks like this has been fixed already:

![image](https://user-images.githubusercontent.com/2385329/90846195-0326ab00-e3ab-11ea-9c40-c1e3c75a3551.png)

**Comment by BWPanda** [comment]
Oh, I see. This issue is about custom blocks created via the Layouts UI, that *aren't* reusable...

![image](https://user-images.githubusercontent.com/2385329/90846510-a972b080-e3ab-11ea-93ad-fd9e223121a7.png)

**Comment by BWPanda** [comment]
Closing as a duplicate of the more general https://github.com/backdrop/backdrop-issues/issues/4558
