### ISSUE TITLE
push, pull, and offset class names mismatch

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#1961]
It looks like our float-fallback stylesheet needs a quick update. The `push-`, `pull-`, and `offset-` class names aren't the same in the flexbox vs float stylesheets.

@wesruv mentioned that:

```
in float grid the classes are: pull-md-#
in flexbox grid the classes are: col-md-pull-#
those should be the same
```

I'm going to take a crack at fixing them and see if it resolves [my other issue](https://github.com/backdrop/backdrop-issues/issues/1962) as well.

**Comment by jenlampton** [comment]
I found the same problem with `offset-` classes as well. Fixing in the same PR.

**Comment by jenlampton** [comment]
I fixed all the classes in the float fallback stylesheet, but since safari loads the flexbox stylesheet, that was unrelated to my other issue.

**Comment by herbdool** [comment]
@jenlampton do you have a link for the pull request?

**Comment by herbdool** [comment]
I tested again in IE11 with this patch. The last column is still getting pushed to the bottom. I set it to the built-in Bartik and built-in Geary layout and same issue. Next step would be test it on a completely new install which I haven't had a chance to try.

**Comment by jenlampton** [comment]
@herbdool I'm facing the same issue, and I think maybe https://github.com/backdrop/backdrop-issues/issues/1973 is not actually a duplicate, as there are other things awry with the float fallback. Returning over there to post my fix :)

**Comment by quicksketch** [comment]
Merged https://github.com/backdrop/backdrop/pull/1440 for 1.4.3. We'll keep working on IE11 in https://github.com/backdrop/backdrop-issues/issues/1973.
