### ISSUE TITLE
[DX] Rewrite rule in .htaccess should not add www before subdomains

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#219]
In Drupal 6, the rewrite rules worked. But since you had to manually specify the whole domain name, multi-site set-up became tedious.

In Drupal 7, the rewrite rules don't work very well.  Even though we've solved the problem for the multi-site edge-case, we've increased frustration for our majority use-case.

In particular, the rule that adds www seems to add it blindly, even before sub-domains where it certainly should not be added.

I would love to see this particular issue solved (perhaps by a smarter regex?) but if we can't find a solution I recommend we return to the Drupal-6 style rewrite rules that will give more success to more people more of the time.

Here's the same issue on [drupal.org](https://drupal.org/node/2207473)

---
PR by @jenlampton: https://github.com/backdrop/backdrop/pull/1875

**Comment by Dinornis** [comment]
@jenlampton 
Looking at the www redirect rules in the latest Backdrop .htaccess, it looks like this has been fixed already, can you please confirm.

**Comment by jenlampton** [comment]
I'm not sure, the rewrite rules look mostly the same to me:

Here are the problematic rewrite rules in Drupal 7:
```
  # RewriteCond %{HTTP_HOST} !^www\. [NC]
  # RewriteRule ^ http://www.%{HTTP_HOST}%{REQUEST_URI} [L,R=301]
```
And here's Backdrop:
```
  # RewriteCond %{HTTP_HOST} .
  # RewriteCond %{HTTP_HOST} !^www\. [NC]
  # RewriteRule ^ http%{ENV:protossl}://www.%{HTTP_HOST}%{REQUEST_URI} [L,R=301]
```

**Comment by jenlampton** [comment]
It's still broken. I uncommented those three lines in the .htaccess on my local dev site, and was redirected from `http://dev.jeneration.com/` to `http://www.dev.jeneration.com/`.

**Comment by Dinornis** [comment]
Sorry, somehow I missed the link to d.o where you explained your use case.

**Comment by jenlampton** [comment]
Well it was really tiny :) no need to apologise!

**Comment by jenlampton** [comment]
I just deployed a backdrop site and ran into this issue again. It's so frustrating. Not only does the rewrite rule add www before a subdomain, but then the redirect gets cached, so even after you undo the change it's really hard to get your browser (ahem, Chrome) to notice the fact that you've turned it off again. :(  Adding the 1.7 milestone because this is a huge annoyance.

**Comment by jenlampton** [comment]
The rewrite rules from the PR have fixed my broken site. Phew.

**Comment by klonos** [comment]
> I think the problem was the `^(.*)$` which was there in D6 and lost in D7?  (though idk what that means, my regex-fu is not strong)

I'm sure you'd have figured this out already, but just in case, `^` means start of a string, `$` means end of a string, `.` means any character and `*` means multiple times.

I still need to test this and wrap my head around the changes, but there are at least two "edge cases" that we should make sure work with the new regex:

1. Domains that have multiple "extensions" like `.co.uk` and `.com.au`
2. local environments that use things like `local.domain` or just `localhost` or `localhost.net`

**Comment by daggerhart** [comment]
Tested and this works well. 

The only real thought I have is that, instead of replacing the existing condition set for redirecting to www, maybe this should be a new set that is commented out with its own description.  Only for the fact that the intent of the PR's condition set is different from the current intent.

Currently the condition set's intent is: "if there is no www at the beginning of the host, add it, regardless of anything else". 

This PR changes that intent to: "if this host is not a subdomain, add www to the beginning of the host".

Personally I don't add www to a subdomain but someone may want that outcome, and this change makes that a little more difficult.  Here is a espousing some pretty solid technical value of using www on your website - http://www.yes-www.org/why-use-www/  Spoiler: cookies

Just to throw out a random use-case:  someone may be building a website for a domain they don't fully control, they have only been given access to a subdomain for the site.  That person may want to add www to the subdomain for reasons specified in the above article, such as using a CDN without sending cookies everywhere.

---

Some random relatively unimportant thoughts:

1. Not sure how much y'all care about this type of thing, but the first change in the PR is just white space at end of line. The space probably shouldn't be there, but the change is unnecessary for the fix.  Some projects care a lot about not making white space changes as part of a bug fix, I don't have strong opinions ¯\_(ツ)_/¯
1. Similar to the previous comment: the `RewriteRule` change is unnecessary for this to work. The following two lines of code are effectively the same thing:
    ```
    # previous rule
    RewriteRule ^ http%{ENV:protossl}://www.%{HTTP_HOST}%{REQUEST_URI} [L,R=301]
    ```
    ```
    # rule in this PR
    RewriteRule ^(.*)$ http%{ENV:protossl}://www.%{HTTP_HOST}/$1 [L,R=301]
    ```

For what it's worth, this could be a single line PR like this:
```
-  # RewriteCond %{HTTP_HOST} !^www\. [NC]
+  # RewriteCond %{HTTP_HOST} ^[^.]+\.[^.]+$
```

**Comment by quicksketch** [comment]
As pointed out, the approach in the PR won't work with country-based domains (co.uk, com.au, etc). So moving this back to needs work.

IMO the problem with both the D7 approach and the attempt here is that it's trying to make a very generic solution, but results in side-effects for specific situations. The D6 approach was not generic: it required you to manually include your site's domain name in the rule. By making the rule site-specific, it does exactly one thing only and avoids any unexpected side-effects.

I would propose that we adopt that approach again, removing the generic handling and providing an example as was in D6.

We can use either the previous D6 example:

```
  # RewriteCond %{HTTP_HOST} ^example\.com$ [NC]
  # RewriteRule ^(.*)$ http://www.example.com/$1 [L,R=301]
```

Or do the approach that uses `%{REQUEST_URI}` instead:

```
  # RewriteCond %{HTTP_HOST} ^example\.com$ [NC]
  # RewriteRule ^ http://www.example.com%{REQUEST_URI} [L,R=301]
```

Personally, I find the first example (exactly from D6) to be the clearer of the two.

**Comment by jenlampton** [comment]
I think going back to the solution we know works (Drupal 6) makes the most sense. I've copied the rules (and documentation) from the Drupal 6 .htaccess file and pushed an updated PR.

**Comment by olafgrabienski** [comment]
As HTTPS-only websites became more common in the last years, can we add corresponding rule examples while we're at changing the rewrite rules?

**Comment by jenlampton** [comment]
> As HTTPS-only websites became more common in the last years, can we add corresponding rule examples while we're at changing the rewrite rules?

Yes, this is a great idea!  Though, I'd hate to see it delay a bug-fix that might otherwise get into 1.7. It would be better to do that in a separate issue. :)

**Comment by olafgrabienski** [comment]
Sure, I agree to not delay the bugfix.

**Comment by jlfranklin** [comment]
HTTPS can be, and probably should be, its own rule, separate from the add/remove www rules.

**Comment by olafgrabienski** [comment]
> HTTPS can be, and probably should be, its own rule, separate from the add/remove www rules.

I've no idea of which rewrite syntax makes sense technically. If it's possible I'd love however to have simply four rules of which I can uncomment the one that fits my needs:

- redirect all users to access the site with the 'www.' prefix
- redirect all users to access the site with the 'www.' prefix and using HTTPS
- redirect all users to access the site without the 'www.' prefix
- redirect all users to access the site without the 'www.' prefix and using HTTPS

**Comment by jenlampton** [comment]
I have moved the conversation about HTTPS redirects over to https://github.com/backdrop/backdrop-issues/issues/2694 so that we can focus on getting this last issue into 1.7.0.  Great work team!

**Comment by quicksketch** [comment]
Thanks, I've merged https://github.com/backdrop/backdrop/pull/1875 into 1.x for 1.7.0.
