### ISSUE TITLE
[UX] - Missing text on Configuration page for content editors

### ISSUE THREAD

**Issue by olafgrabienski** [backdrop/backdrop-issues#2239]
As a content editor, you're able to reach the Administration overview page using the relevant Breadcrumb link. Although the custom Editor role isn't configured very permissive, an editor sees the following links on the Administration page:
- Content
- Structure
- Configuration

**Content** is just fine. On **Structure**, as an editor you see the text "You do not have any administrative items.". It's strange that you see the Structure link at all, but there's at least the text.

On **Configuration** you see nothing.

![screencast-backdrop-editor-admin-pages](https://cloud.githubusercontent.com/assets/14188307/18909298/56005b54-8573-11e6-8dab-e3e4f6b2533d.gif)

**Suggestions:**

As a quick fix, I propose to add a text to the Configuration page as well, for instance "You do not have any configurational (?) items."

In the medium term we should remove the not useful thus confusing links. Has there been a discussion about that topic elsewhere?

**Comment by klonos** [comment]
> ..."You do not have any configurational (?) items."

I think we use "configurable", but anyways it seems to me that this is a permissions-related issue as these items are controlled by the menu system AFAIK and as you pointed out, their links shouldn't be in that list in the first place.

**Comment by klonos** [comment]
>...Has there been a discussion about that topic elsewhere?

I follow the issue queues as best as I can and I can't remember this being mentioned elsewhere. So this is definitely not a duplicate if that's what you're asking.

**Comment by klonos** [comment]
> ...I can't remember this being mentioned elsewhere.

We've fixed this in Basis (#3371) but we should implement it in a theme-agnostic way. Ideally, these links where the user does not have access to any sub-pages, should not be shown at all. (I thought that we already had an issue for that, but can't find it now)

**Comment by klonos** [comment]
...now that I'm checking https://github.com/backdrop/backdrop/pull/2356/files it seems that the code change to fix things was in the System module. Not sure why it only works as expected with Basis and not in Seven 🤔

**Comment by olafgrabienski** [comment]
> Not sure why it only works as expected with Basis and not in Seven

I just wanted to confirm that it's still an issue in Seven. Also not sure why.

Hm, when you look at the HTML, in *Basis* both the page title and the "You do not have any administrative items" text are in `l-wrapper`. In *Seven*, the page title is in `l-header`.
