### ISSUE TITLE
[UX] User accounts still referred to as "User" in views UI

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#2566]
At various places in the Views UI user accounts are still referred to as "Users".  We should update views UI to be consistent with the rest of core.

Example: `Link this field to its user`

**Comment by klonos** [comment]
...I'll take a crack at this later tonight 😉

**Comment by opi** [comment]
Related to https://github.com/backdrop/backdrop-issues/issues/2100

**Comment by stpaultim** [comment]
#OpenForce2022 participants. If you are interested in this issue, the goal is to replace the word "user" with other terms like "author", "person," etc. 

In this case, we're looking at the views UI, which can be found here:
https://github.com/backdrop/backdrop/tree/1.x/core/modules/views_ui

**Comment by RakeshPotnuru** [comment]
@stpaultim 
I think this issue is resolved
[https://github.com/backdrop/backdrop/blob/1.x/core/modules/views_ui/views_ui.module#L734](https://github.com/backdrop/backdrop/blob/1.x/core/modules/views_ui/views_ui.module#L734)

**Comment by stpaultim** [comment]
@RakeshPotnuru - No, I still see the issue.

![image](https://user-images.githubusercontent.com/3144571/158078659-34b68912-a9f0-4c70-9025-ebf614bb9868.png)

I will add steps to recreate in the original issue.

**Comment by aniketh-varma** [comment]
Hi, I would like to work on this issue.

**Comment by indigoxela** [comment]
Hi @aniketh-varma,

yes, sure, you're welcome! Let us know, if you need any guidance regarding code or Github or anything related to the workflow.
