### ISSUE TITLE
No error highlighting on form checkbox or radio input types

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#289]
The Drupal 'form_set_error()' function generates an error message for the top of the page and highlights the contents of the field which contains the error in red. Trouble is that highlighting input elements (checkboxes and radio buttons) does not work consistently across all browsers.

In light of this situation we should move the error highlighting for these input form types to the element around inputs for checkbox or radio types. [d.o issue](https://www.drupal.org/node/222380)

---

~~PR https://github.com/backdrop/backdrop/issues/1744~~ (merged)
Follow-up PR https://github.com/backdrop/backdrop/pull/1752

**Comment by jenlampton** [comment]
new PR

**Comment by quicksketch** [comment]
The PR here solves the problem, but the result is still incredibly ugly. At the very least, perhaps we could create better styling for the Basis and Seven themes to make it consistent with those themes styling. Perhaps @wesruv would be able to take a look at this?

**Comment by jenlampton** [comment]
@quicksketch can we merge this as-is to fix the bug, and then add a follow-up to make it prettier?  I would hate for the bug to remain in 1.6 because we thought it was an ugly solution :)

**Comment by serundeputy** [comment]
This fixes the immediate bug.

Merged into `1.x` and `1.5.x` will ship with `1.5.3` and `1.6.0`.

I'll open a follow up issue to iterate on the theming of the error highlighting for checkboxes and radio buttons.

**Comment by jenlampton** [comment]
Actually, it looks like this commit has some issues. The class `.error` now has a pink background where it didn't before, and that's painting some funny colors around error highlighted selects, for example: 
![screen shot 2017-01-14 at 10 48 29 pm](https://cloud.githubusercontent.com/assets/397895/21960815/cec7b284-daab-11e6-99ff-98cea6578072.png)

**Comment by serundeputy** [comment]
@jenlampton have a look at this PR if you will: https://github.com/backdrop/backdrop/pull/1752

It increases the specificity of the background color css to `.messages.error`.

**Comment by quicksketch** [comment]
Thanks @serundeputy. I'm a little worried about the use of "error" for both messages and form validation. Increasing the specificity on the CSS does solve the immediate problem, but existing sites and themes will have already built assumptions on where the error class has been used (previously just on messages and directly on form elements) and now we're adding another location (element wrappers).

If we used a different class on the wrapper, that would avoid the need to increase specificity and avoid any existing conflicts. Considering the element wrappers are all prefixed with `form-` already (e.g. `form-text`, `form-item`), we could change the class to `form-error` on the wrapper instead. Would that work?

**Comment by serundeputy** [comment]
@quicksketch I've updated the PR to use `form-error` class and remove the `.messages` prefix from the `.error` class.  I think this is now additive and will not effect existing installs.

https://github.com/backdrop/backdrop/pull/1752/files

**Comment by quicksketch** [comment]
Thanks this looks great @serundeputy! Though I found that a single checkbox still doesn't get the border like radios and multiple checkboxes do. Left a comment on the PR.

**Comment by quicksketch** [comment]
![screenshot from 2017-01-15 12-31-41](https://cloud.githubusercontent.com/assets/100206/21965945/a02019a8-db1e-11e6-9f0f-479137751be3.png)

**Comment by serundeputy** [comment]
Ok; added `.form-type-checkbox.form-error` selector into the mix.
![screen shot 2017-01-15 at 3 39 55 pm](https://cloud.githubusercontent.com/assets/6763671/21966004/00c3c7ea-db39-11e6-8c42-61bffdca0a3a.png)

**Comment by quicksketch** [comment]
Yeah, now we just have the issue that the individual radios/checkboxes within a group shouldn't get the `error` class on each one (causing the red background).

**Comment by jenlampton** [comment]
Looking good, nice job guys 👍

**Comment by quicksketch** [comment]
Okay I think we have it now in the latest PR.

![screenshot from 2017-01-15 13-54-04](https://cloud.githubusercontent.com/assets/100206/21966544/3084fae4-db2a-11e6-9a76-75967f3f2e91.png)

**Comment by quicksketch** [comment]
I've merged in https://github.com/backdrop/backdrop/pull/1752 into 1.x and 1.5.x.
