### ISSUE TITLE
[UX] Add Phone field to Contact forms

### ISSUE THREAD

**Issue by ghost** [backdrop/backdrop-issues#3047]
The current proposal is to add a few additional fields to contact forms, with settings for them:

1) markup or message field, like a body (setting: textarea field - default to empty)
2) phone number field (setting: on/off checkbox - default to off)

# Original issue

I'd love to see the Contact module/form made fieldable. I know that Webform exists and is often used for this purpose, but it does a lot of extra stuff that is unnecessary when you simply want to add a Phone field to the existing Contact form (for example).

I envisage something like this:

- Fields can be added in the same way as nodes
- Fields can be re-ordered
- Contrib modules (like Captcha) can add their fields which makes them re-orderable too
- Contact settings (like recipients/categories) can be managed on a form like the Create Content Type form
- Maybe go further and make Contact an entity, and then 'categories' become bundles (e.g. you can add different fields for different departments; so that when someone contacts your support department, they can also enter their customer ID)

**Comment by jenlampton** [comment]
> I'd love to see the Contact module/form made fieldable.

I'm only half on board with this idea.

> Maybe go further and make Contact an entity, and then 'categories' become bundles

Woah, hold your horses there, this sounds an awful lot like unnecessary abstraction, as well as using tools that aren't quite meant for this job. Let's not go the way of Drupal :) 

The biggest downside to using Field API "fields" is that they store data, and if we introduce one place in core where they don't, that's going to be very confusing for people.

Webform is a fantastic, feature-complete module that replaces an email-sending core module with a data-storing alternative, and that kind of feature addition is best left to contrib. I'd prefer we not blur those lines too much.

I think we can achieve the result you are after by adding a few additional form API elements to the contact form, with checkboxes to turn them on/off, and yes, tabledrag to re-order them. As long as we add a hook for captcha and other modules to put their things into the tabledrag list, these elements could also be re-orderd.

This is a simpler solution that more people will understand (both code and UI) and smaller and more manageable change. It could even go in any time in the 1.x cycle.

We'll need to decide on the most common ones - phone number is a good one. Are there any others you add frequently?

**Comment by BWPanda** [comment]
Sure, sounds like a good compromise.

Phone, and How did you hear about us? are the only fields I've been asked to add, but I think that second one is better in Webform. Maybe Address? What do others think?

**Comment by jenlampton** [comment]
Let's look at the WordPress contact widget and see what they include :)

**Comment by opi** [comment]
:+1: on not trying to clone webform in core ;) KISS

:+1: for toggable additionnal fields, like phone

:-1: on address, having a flexible and complete address field which works for any country is hard. The compromise could be another textarea field, with an editable label to fit *address* or *How did you hear about us* needs. But not required IMHO. Again, webform exists and is perfect for advanced (contact) forms !

:+1: for *markup* or *message* field, like a body. I often need to add some custom text before the form, and do it with a block or a hardcoded `form_alter`

:+1: of course on draggable order ! (https://github.com/backdrop/backdrop-issues/issues/3052 needs review fore a start :p )

**Comment by klonos** [comment]
#3193:

> ...
>As a Drupal/Backdrop newcomer who does not know what contributed modules are available out there, it would be helpful to be pointed to the right direction. This following example promotes the Webform module in the core Contact module settings page (`/admin/structure/contact`):
>
><img width="896" alt="screen shot 2018-07-10 at 5 20 28 am" src="https://user-images.githubusercontent.com/2423362/42471440-076d6f66-8401-11e8-973b-c5cae5f27c50.png">
>
>As a person that tries Backdrop for the first time, one would not be left with a "Seems I can't do this with Backdrop 😞 👎" feeling, but with a "Oh, Backdrop only offers this basic functionality OOTB, but I can do more it using this addon! 💡😄 👍".

**Comment by jenlampton** [comment]
I love this idea, but this implementation is too much text. Can we remove `that include...` through `...future reference`?

**Comment by jenlampton** [comment]
Another thought.. By adding these info messages everywhere, we're almost re-inventing the help module, only in this instance we aren't giving more advanced users any way to turn off these messages. Though this will improve the first-time user experience, it will frustrate the pros. 

Do we want to revisit adding something like help module to core again, but maybe have it set these info messages where useful, instead of doing what it did before?

**Comment by BWPanda** [comment]
> +1 for markup or message field, like a body.

If we add this, which I think is a good idea, can we then also add an Edit tab to the Contact page (like nodes have) which takes the logged-in user to the Contact forms settings page?

I think users are used to seeing Edit tabs above content, and when the Contact form doesn't have one it can be tricky to work out how to edit it...

**Comment by stpaultim** [comment]
I've added the "Good First Issue" tag with some hesitation. I did so, because this part seems manageable for a new contributor that is able to look at how fields have been added to other forms and extrapolate. 

```
The current proposal is to add a few additional fields to contact forms, with settings for them:

markup or message field, like a body (setting: textarea field - default to empty)
phone number field (setting: on/off checkbox - default to off)
```

**Comment by BWPanda** [comment]
Here's an initial PR: https://github.com/backdrop/backdrop/pull/3374

![image](https://user-images.githubusercontent.com/2385329/95935083-1f305100-0e1e-11eb-87dc-7970e1d90968.png)

![image](https://user-images.githubusercontent.com/2385329/95935138-4555f100-0e1e-11eb-89d0-cc0292d812c9.png)

I made the phone number setting a select list instead of a checkbox as we need a way to specify whether it should be a required field or not.

I didn't add the markup field, since I'm wondering if we should just leave that to blocks/layouts...?
And I didn't do the re-orderable fields thing as I'm not sure where/how to do that... Suggestions welcome.

**Comment by olafgrabienski** [comment]
> I didn't add the markup field, since I'm wondering if we should just leave that to blocks/layouts

In my opinion, having a markup / long text / body field would be very helpful. Providing it as a block is quite complicated and needs also different permissions.

**Comment by indigoxela** [comment]
Way too many related tests are failing and/or are throwing exceptions.

**Comment by BWPanda** [comment]
A lot of exceptions were the `.htaccess` copying problem we fixed in another issue, so I merged `1.x` into the PR branch to fix those. Then I made a simple change to fix the other exceptions.

**Comment by indigoxela** [comment]
@BWPanda did you forget to push something?

In the testbox I still get: `426 passes, 44 fails, 17 exceptions` when running the contact tests via UI.

And visiting /contact gives me a wsod.

**Comment by BWPanda** [comment]
All tests passed on my local (via the UI). Only the PHP5 tests have failures in GitHub and they seem to be because it's getting 500 errors. Not sure why...

**Comment by indigoxela** [comment]
>  it's getting 500 errors. Not sure why...

This is [a wsod](http://3374.backdrop.backdrop.qa.backdropcms.org/contact).

Neither am I, and I don't see anything obviously problematic for php 5.3...
Try to turn it off and on again? (Our usual approach :smirk: )

BTW: I left a comment (question) at your PR.

**Comment by BWPanda** [comment]
Bah! I don't know what's going on. Tried turing it off and on again, opening a [new PR](https://github.com/backdrop/backdrop/pull/3380), but it's still WSOD-ing the contact form... :cry:

**Comment by indigoxela** [comment]
>  it's still WSOD-ing the contact form

Yes, both, site wide and personal contact form. I did a quick local check on php 5.6 - no problem. What the...

Another thought: The naming of your setting seems a bit ambiguous to me. I would have expected "contact_phone", but you use just "phone". But I'm not sure, how the conventions regarding config items are, you probably know it better.

**Comment by BWPanda** [comment]
Updated PR to use 'tel' field type instead of 'textfield' (as per @indigoxela's suggestion in the PR). But PHP5 tests still failing for unknown reasons, and now Zen's mucking up too. I give up.

**Comment by indigoxela** [comment]
> Updated PR to use 'tel' field type instead of 'textfield'

Yes, but only in one of the two fields. :wink: 

> PHP5 tests still failing for unknown reasons, and now Zen's mucking up too. I give up.

So... , now it a 404. Oh Zen.CI!

@BWPanda I can really understand your frustration.

**Comment by BWPanda** [comment]
PR updated again, thanks.

**Comment by indigoxela** [comment]
With some help from the community we were able to tame the php 5.3 dragon. :dragon: 

Everything works as expected now. Here are screenshots from the sandbox:

Admin form items:
![contact-admin-form](https://user-images.githubusercontent.com/842066/97081842-75af4380-1605-11eb-88a5-522344574071.png)

Contact form:
![contact-form](https://user-images.githubusercontent.com/842066/97081847-7e077e80-1605-11eb-9803-11a01f29ccf6.png)

**Comment by olafgrabienski** [comment]
Nice, I've also tested the `tel` input with my phone (many phones provide a special keyboard for the `tel` input).
Looks good:


<img src="https://user-images.githubusercontent.com/14188307/97082835-d1c99600-160c-11eb-9548-b9e135eb4ab6.png" alt="screen-backdrop-pr-3380-contact-field-tel" style="max-width:100%;" width="375">

**Comment by herbdool** [comment]
Either we make this issue META or we retitle it so it's only about adding a telephone field. Either way there can be follow up issues for adding a message field, and allowing reordering.

**Comment by BWPanda** [comment]
Have re-titled this issue. There's already a meta here: https://github.com/backdrop/backdrop-issues/issues/3023

**Comment by herbdool** [comment]
Code looks good to me.

**Comment by BWPanda** [comment]
Thanks @indigoxela, @olafgrabienski & @herbdool for your help with the PR. I've merged https://github.com/backdrop/backdrop/pull/3380 into 1.x.

And thanks for @docwilmot who also reviewed the PR, but I forgot to mention him in the commit message, sorry!
