### ISSUE TITLE
[SEO][WP] Add a lazy-loading option for image fields

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#3659]
**Description of the need**

Native `<img>` lazy-loading is coming to the web! https://bit.ly/loading-attribute … `<img loading=lazy>` defers offscreen images until the user scrolls near them. Shipping in Chrome ~75 https://bit.ly/loading-i2s 

This was one of the recommendations Google PageSpeed gave me for one of my Backdrop sites.

We should support this in Backdrop core!

---

References:
* https://css-tricks.com/native-lazy-loading/
* https://web.dev/native-lazy-loading/

---

Advocate: @klonos 

---

PR that adds a global setting under 'Performance': ~https://github.com/backdrop/backdrop/pull/3256~

PR that adds a setting for image fields: https://github.com/backdrop/backdrop/pull/3273

**Comment by BWPanda** [comment]
My first thought is that it'd be nice to have an option to turn this on/off (since it effectively changes how things have been working up to now, and some people don't necessarily like change), but then explaining that that option will only affect certain browsers/versions, blah blah blah could be tricky. So next thought is to include a polyfill for all other browsers, so then on/off option works for everyone. But then this sounds more like a contributed candidate than a core feature... But that's just my 2c.

**Comment by klonos** [comment]
I don't think that anyone will complain for this, since it sounds more like an improvement rather than an undesired change. Do we have any use case where someone has reported that this has broken things for them?

...also, what are our Drupal brethren doing about this?

Having said that, I wouldn't mind a global option for it. Under "Performance" seems proper.

**Comment by olafgrabienski** [comment]
> Do we have any use case where someone has reported that this has broken things for them?

Don't know if it will actually break things, but https://groups.google.com/a/chromium.org/forum/#!topic/blink-dev/jxiJvQc-gVg and https://docs.google.com/document/d/1e8ZbVyUwgIkQMvJma3kKUDg8UUkLRRdANStqKuOIvHg mention some risks.

If we implement it site-wide, the default should be `auto`, leaving the decision to the browser (which seems to be the same as not setting the attribute at all).

More thoughts: In HTML `loading="lazy"` would be an option for every image. In my opinion, Backdrop site owners / architects, and content editors should also be able to control, if and how the attribute is used. I guess that means, in addition to a global option, loading attribute options could be useful for the CKEditor image dialog, for image field (or display) settings and for views fields.

**Comment by jenlampton** [comment]
> My first thought is that it'd be nice to have an option to turn this on/off (since it effectively changes how things have been working up to now

Well it is just an attribute, so it should be easy enough to turn on/off by adding/removing the attribute when any image is rendered. But I do think -- if not otherwise specified -- all images should lazy-load.

> Backdrop site owners / architects, and content editors should also be able to control, if and how the attribute is used.

I could see this being a good candidate for contrib. My guess is that more than 80% of people would rather have have their sites load quickly than have images people can't see load first. However, it should be simple enough to integrate the option with all existing image fields so people can disable that on a per-image basis.

**Comment by klonos** [comment]
I think that lazy-loading by default, with a global option under "Performance" should be core; per-image field instance can be contrib.

**Comment by olafgrabienski** [comment]
> I do think -- if not otherwise specified -- all images should lazy-load.

> lazy-loading by default, with a global option under "Performance" should be core

I've skimmed through some of the linked information about the new attribute, and I'm still not sure if there will be unwanted side effects at the beginning, when `loading=lazy` is the default. What about starting with leaving the default to `loading=auto`, with the goal to test the `lazy` setting (and also `eager`) in real world situations? If there are no serious problems, we can iterate and change the default.

**Comment by klonos** [comment]
> What about starting with leaving the default to `loading=auto` ...

That could work too. Safest also. If at a later point we are more certain that `loading=lazy` is safe to use, we can change that to be the default for new installations. Perhaps for existing sites we can consider using `info` type messages to let people know that they can switch.

**Comment by jlfranklin** [comment]
Tracking pixels, hidden icons in drop down menus that may cause the menu to redraw multiple times as lazyload images come in, sprite sheets, collapsed form fields... there are a number of cases where the web developer may want them to load even though they're hidden.

When adding a new feature, the default setting should always be the previous behavior.  Otherwise, Backdrop will earn a reputation for breaking sites on minor-number updates.

**Comment by jenlampton** [comment]
> When adding a new feature, the default setting should always be the previous behavior. 

If we use @klonos's recommendation of having a single site-wide on/off checkbox for this, then it would be easy to set to off for existing sites, and on for new ones.

**Comment by klonos** [comment]
FTR, the freshly-released [WordPress v5.5 supports that feature OOTB](https://wordpress.org/news/2020/08/eckstine):

> ## Speed
>Posts and pages feel faster, thanks to lazy-loaded images.
>
>Images give your story a lot of impact, but they can sometimes make your site seem slow.
>
>In WordPress 5.5, images wait to load until they’re just about to scroll into view. The technical term is ‘lazy loading.’
>
>On mobile, lazy loading can also keep browsers from loading files meant for other devices. That can save your readers money on data — and help preserve battery life.

**Comment by klonos** [comment]
>Tracking pixels, hidden icons in drop down menus that may cause the menu to redraw multiple times as lazyload images come in, sprite sheets, collapsed form fields... there are a number of cases where the web developer may want them to load even though they're hidden.

I would like us to test if these are actual problems, or assumptions.

>>When adding a new feature, the default setting should always be the previous behavior.
>
>If we use @klonos's recommendation of having a single site-wide on/off checkbox for this, then it would be easy to set to off for existing sites, and on for new ones.

Yes! Let's please do this, and let's add an on/off switch under `admin/config/development/performance`, and have it on only for new sites.

**Comment by klonos** [comment]
PR up for review: https://github.com/backdrop/backdrop/pull/3256

Most of the "system" images, like the admin bar icons and the hero block image, are being set in CSS (using `style="background-image:url(/files/hero/...);"` for example), so they are not affected by this change. Only images that are rendered via `theme_image()` get the `loading="lazy"` attribute. If a developer needs to disable that for a specific image, they can specify the `loading` attribute when calling `theme_image()`:

```php
$output = theme('image', array('attributes' => array('loading' => 'eager')));
```

No update hook added to the PR, so existing sites should be left intact, and will need to opt-in for the feature.

For now, I've added the checkbox that controls this under Configuration -> Development -> Performance:

![image](https://user-images.githubusercontent.com/2423362/90452981-1e1dc480-e0f8-11ea-830e-80ff602d0ef9.png)

Let me know if you think that it deserves its own dedicated fieldset, or it should live in a different section in the admin UI.

**Comment by klonos** [comment]
...my initial thinking was that hero blocks are usually placed at the top of the page, so they are likely to be within viewport at all times soon as the page loads, so lazy-loading does not make sense there. I then thought of @stpaultim and #4095, and realized that there are use cases where multiple hero blocks may be placed on a single page. Since hero images are large, lazy-loading those that are further down the viewport will have legit performance/loading gain, so I have actually enabled hero block images to also take advantage of this (if enabled).

**Comment by indigoxela** [comment]
The PR still needs work. Many tests are currently failing.

**Comment by klonos** [comment]
Tests fixed.

**Comment by indigoxela** [comment]
> not all browsers support this feature, but to clarify, in that case the loading attribute will simply be ignored

Yep, that's correct. And I belief the time is right to add this feature to Backdrop.

My hint was rather meant to clarify that not all testers might see what they expect (lazy loading images) - in case they test with a browser that has no support for the attribute yet.

@klonos I left another comment on your PR - just a suggestion.

**Comment by indigoxela** [comment]
Oops, it just came to my mind that we also need to implement hook_update_N to add the setting to system.core.json for existing sites. Sorry that I didn't think of that earlier.

**Comment by klonos** [comment]
> I left another comment on your PR - just a suggestion.

Yup, I was planning to add a test - @hosef mentioned the same.

>...we also need to implement hook_update_N to add the setting to system.core.json for existing sites.

I believe that the consensus was to not do that. @jlfranklin expressed concerns that this might break existing sites, so I've added the checkbox that existing site can use to opt-in for the feature. If there's general agreement that there should be an update hook, then I'm happy to add one.

**Comment by indigoxela** [comment]
> I believe that the consensus was to not do that. @jlfranklin expressed concerns that this might break existing site

Ah, OK, I didn't mean to set it to TRUE, but to set it to FALSE for existing sites. But add it to system.core.json, as it's a new config item.

**Comment by klonos** [comment]
@indigoxela what we should really have is something like #1912, so we could show a message with a checkbox on existing sites, to allow site admins to enable the new feature or skip.

**Comment by stpaultim** [comment]
This looks like it could be a nice addition to 1.17. Keep up the good work!

**Comment by quicksketch** [comment]
> Ah, OK, I didn't mean to set it to TRUE, but to set it to FALSE for existing sites. But add it to system.core.json, as it's a new config item.

Agreed, we should add an update hook just to get the value defined (as `FALSE`) so the same behavior is maintained, but we get the value specified in config.

Does this really make sense as a global option? If you just mark _all_ images lazy, what is that accomplishing? It seems like users would need/want images above the fold to load immediately. Though if they're within the viewport, will the browser load them after everything else anyway?

**Comment by stpaultim** [comment]
I found [this article](https://web.dev/lazy-loading-best-practices/) which suggests:

> It may be tempting to lazy-load every single media resource on the page with JavaScript, but you need to resist this temptation. Anything resting above the fold shouldn't be lazy-loaded. Such resources should be considered critical assets, and thus should be loaded normally.

This seems relevant to the discussion we had during dev meeting about whether or not it's good to set ALL images to lazy load.

https://web.dev/lazy-loading-best-practices/

**Comment by klonos** [comment]
Thanks @stpaultim but I'm not convinced that that article is referring to native browser lazy-loading. It seems to be talking about JavaScript implementations ...is that what the browsers use behind the scenes to implement lazy-loading? 🤷

**Comment by indigoxela** [comment]
I'd like to share my findings regarding browser implementations when I was testing. They do it differently - who would have expected anything else :wink: 

In Firefox the images get loaded, when the image comes into the viewport - means that one sees the alt text for a very short time if scrolling fast. In Chrome(ium) the images get loaded before that - it tries to load anticipating.
At least in FF images that never reach the viewport (user didn't scroll down there), don't get loaded at all.
Images that are already *in* the viewport when loading the page get loaded immediately in both browsers.

> Does this really make sense as a global option?

Function theme_image() is widely used, not only for image fields. Where could be better places if it weren't a global option?

**Comment by jenlampton** [comment]
> Where could be better places if it weren't a global option?

Today @quicksketch recommended that it should be a setting on image fields. I'm going to take a stab at updating the PR to limit its affect.

**Comment by stpaultim** [comment]
It wasn't clear to me where to look for this immediately. So here is a screenshot.

![Screen Shot 2020-08-30 at 12 44 53 AM](https://user-images.githubusercontent.com/3144571/91652166-08928e00-ea5a-11ea-9e99-35c11515478d.png)

**Comment by indigoxela** [comment]
Works for me, but I left a comment on the PR.

There's currently no entry yet for this setting in the formatter summary:

![loading-summary](https://user-images.githubusercontent.com/842066/91657795-3f04f300-eac4-11ea-82b6-c5649a5dc200.png)

**Comment by klonos** [comment]
Thanks @jenlampton 👍 ...I've closed my PR in favor of yours.

> Today @quicksketch recommended that it should be a setting on image fields.

Also on text formats as a filter. If not as part of this PR, then we should file a follow-up.

**Comment by klonos** [comment]
...the main functionality (adding the `loading` attribute to images) works as expected per content type display 👍 ...once @indigoxela's comments are addressed (`auto` instead of `normal` + summary text in the formatter), this is RTBC from me.

**Comment by jenlampton** [comment]
> Also on text formats as a filter. If not as part of this PR, then we should file a follow-up

Yes, please, can you create another issue? 

> ...once @indigoxela's comments are addressed

Done, and I added tests for lazy/eager loading!

**Comment by indigoxela** [comment]
@jenlampton many thanks for updating the PR and for adding tests.

One thing still isn't addressed: [hook_field_formatter_settings_summary()](https://api.backdropcms.org/api/backdrop/core%21modules%21field_ui%21field_ui.api.php/function/hook_field_formatter_settings_summary/1)

There's no summary text yet, as proposed in my previous comment: "Loading: xxx"
See the [screenshot](https://user-images.githubusercontent.com/842066/91657795-3f04f300-eac4-11ea-82b6-c5649a5dc200.png) for explanation.

**Comment by klonos** [comment]
> Yes, please, can you create another issue?

Done 😉

**Comment by klonos** [comment]
> ...we should also make sure that this works with Views if the view format is set to show individual fields instead of "content".

Tested this in the current PR, and it works 🎉 :

![image](https://user-images.githubusercontent.com/2423362/91731152-4654fb00-ebaf-11ea-9f93-329467ad38a3.png)

**Comment by jenlampton** [comment]
> + summary text in the formatter

Ah, sorry. Not sure how I missed that. Pushed an updated PR! 
<img width="1232" alt="Screen Shot 2020-08-31 at 10 51 13 AM" src="https://user-images.githubusercontent.com/397895/91750421-ee4ed200-eb77-11ea-8714-43fd43139e22.png">

**Comment by herbdool** [comment]
Looks good now - tested and reviewed the code.

**Comment by quicksketch** [comment]
I merged https://github.com/backdrop/backdrop/pull/3273 into 1.x for 1.17.0. Thanks @jenlampton, @klonos, @indigoxela, @BWPanda, @stpaultim, @herbdool, and @olafgrabienski!
