### ISSUE TITLE
[UX] Indicate vocabulary when editing a term

### ISSUE THREAD

**Issue by laryn** [backdrop/backdrop-issues#3811]
**Description of the need**
I've found a number of times that a website will have a term listing page as a menu item. Then when I go to the page, it shows an edit button so I can jump straight to editing the term. On the edit page, however, there is no indication which vocabulary the term belongs to, which would be useful, I think. (e.g. in editing a node, you see the content type in the title: "Edit Post [title of content]")

![Screen Shot 2019-05-23 at 10 10 24 AM](https://user-images.githubusercontent.com/871421/58264591-bb4a4b80-7d43-11e9-9ec0-500bce69f7cd.jpg)

**Proposed solution**
Instead of just "Edit term [term name]" perhaps we could use "**Edit [vocab] term [term name]**"?

---

Side note: Another "term editing experience" issue (completely different except it relates to term editing as compared to node editing) just noted here in case it is easy to fix at the same time: https://github.com/backdrop/backdrop-issues/issues/1243

----

PR: https://github.com/backdrop/backdrop/pull/3484

**Comment by laryn** [comment]
Here's how the node form sets the title:

> `backdrop_set_title(t('Edit @type %title', array('@type' => $type_name, '%title' => $node->title)), PASS_THROUGH);`

The term edit page title is done this way at the moment:

> `backdrop_set_title(t('Edit term %term_name', array('%term_name' => $term->name)), PASS_THROUGH);`

**Comment by laryn** [comment]
PR https://github.com/backdrop/backdrop/pull/3484

**Comment by BWPanda** [comment]
Code looks good and testing the PR sandbox shows it works as expected. Good job @laryn!

My only thought is that Node pages don't include the word 'node' or 'content'... Just "Edit [type] [title]". If we were to copy that format exactly, Term pages would show something like "Edit Tags mytag" (instead of "Edit Tags term mytag").
That doesn't seem to work well for the default 'Tags' vocabulary, but any user could easily create a content type with a plural name and it'd be the same for nodes.

So I guess I'm asking if we want to copy the node format exactly and remove the word 'term' from the title, or keep it...?
If we keep it, then I'd say this PR is RTBC.

**Comment by olafgrabienski** [comment]
> I'm asking if we want to copy the node format exactly and remove the word 'term' from the title, or keep it

I'd suggest to keep the word `term`, this way it's very clear you're editing a term and not node content. It also helps to differentiate the UI if a vocabulary has the same name as a content type.

**Comment by philsward** [comment]
What about the breadcrumb? It always bugged me that the breadcrumb didn't have the vocab.

Can this discussion also be applied to the term/add page as well?

**Comment by BWPanda** [comment]
> What about the breadcrumb? It always bugged me that the breadcrumb didn't have the vocab.

I would suggest that be a separate issue, as this one's about adding the Vocabulary name to the page title.

> Can this discussion also be applied to the term/add page as well?

Ooh, good point! The only indication of what Vocabulary you're adding a new term to is the small breadcrumb (or the URL path). We should definitely add the Vocab name to the page title here too (and that's certainly within the scope of this issue).

@laryn Care to update your PR to account for the Term Add page too?

**Comment by laryn** [comment]
@BWPanda @philsward I've updated the PR to also add to the "Add term" page.

**Comment by philsward** [comment]
Just checked and the breadcrumb is already good to go so no issue needed there. I'm still getting used to the things BD has fixed that Drupal hasn't. 😉

**Comment by BWPanda** [comment]
Looking at the code, $vocabulary can be passed in, but if its not then its loaded from the term. It looks like there are multiple places where this happens.

I recommend moving that loading to the top of the function so its only needed once. That'll help clean this function up a bit.

**Comment by laryn** [comment]
Third time's the charm? ;)

**Comment by klonos** [comment]
> Third time's the charm? ;)

Or maybe a 4th (sorry)...

I've made a suggestion re the page titles:

- Change the term add form title:
  - from `Add @vocab_name term`
  - to: `Add term to the %vocab_name vocabulary` (indicate what is being added first)
- Change the term edit form title:
  - from `Edit @vocab_name term %term_name`
  - to: `Edit term %term_name in @vocab_name vocabulary` (put the name of the thing that's being edited first)

PS: @laryn can you please add the "fixes" thingy in the PR summary, so that it's properly linked here?

**Comment by BWPanda** [comment]
I'm not sure I agree with @klonos' suggestions re. the title re-wording... They seem unnecessarily long and don't follow the same format as the node page titles...

In any case, I've also requested a small, un-related change to the PR.

**Comment by klonos** [comment]
> They seem unnecessarily long

How about prepending `Vocabulary @vocab_name:` to them then:

- `Vocabulary @vocab_name: add term`
- `Vocabulary @vocab_name: edit term %term_name`

**Comment by philsward** [comment]
![image](https://user-images.githubusercontent.com/3436110/104117930-a476b500-52ea-11eb-921f-5d9e757fbf9c.png)
![image](https://user-images.githubusercontent.com/3436110/104117944-b9ebdf00-52ea-11eb-838a-5409af0acdb1.png)

vs

![image](https://user-images.githubusercontent.com/3436110/104117959-dee05200-52ea-11eb-92b8-50f6c2422560.png)
![image](https://user-images.githubusercontent.com/3436110/104117952-cff99f80-52ea-11eb-9fa1-44444806670d.png)

additional

![image](https://user-images.githubusercontent.com/3436110/104118007-46969d00-52eb-11eb-99de-713e4cd486dc.png)
![image](https://user-images.githubusercontent.com/3436110/104118014-54e4b900-52eb-11eb-9dbf-887d6c26394b.png)


For simplicity, I think I like:

@vocab_name: add term
@vocab_name: edit term %term_name

Side note to my earlier comment about breadcrumbs: It's only fixed for "Add term". It still needs fixed for "Edit term". Will create issue if I can't find one.

**Comment by laryn** [comment]
I've updated the PR with the latest suggestion. I think the parallelism works well:

> ![Screen Shot 2021-01-12 at 11 59 13 AM](https://user-images.githubusercontent.com/871421/104353597-ad73ac00-54cd-11eb-8eac-e3f7dd9a3643.jpg)

> ![Screen Shot 2021-01-12 at 11 59 21 AM](https://user-images.githubusercontent.com/871421/104353607-b2d0f680-54cd-11eb-8991-488c02da7e1a.jpg)

> ![Screen Shot 2021-01-12 at 11 59 29 AM](https://user-images.githubusercontent.com/871421/104353626-b82e4100-54cd-11eb-8bf4-614179d77905.jpg)

**Comment by klonos** [comment]
Thanks @laryn 🙏 ...code looks good, and things work as expected. RTBC 👍

**Comment by quicksketch** [comment]
I merged https://github.com/backdrop/backdrop/pull/3484 into 1.x. To avoid the string update for translations, I didn't pull it into 1.17.5. 1.18.0 will be out tomorrow with this change. Thanks folks!
