### ISSUE TITLE
[UX] Text format edit form: hide "Filter processing order" and "Filter settings" sections when empty

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#3986]
While working on #1575, I have noticed that when adding/editing a text format, the "Filter processing order" and "Filter settings" sections are being rendered, even if there is nothing in them:

![Screen Shot 2019-08-22 at 5 53 27 pm](https://user-images.githubusercontent.com/2423362/63525381-48996980-c506-11e9-8a12-6a5c1bb5a35c.png)

...we should be using `#states` to show them only when it makes sense.

---
PR by @klonos: https://github.com/backdrop/backdrop/pull/2825

**Comment by klonos** [comment]
PR up for review: https://github.com/backdrop/backdrop/pull/2825

There is one annoyance remaining, but it's tricky to fix: the "Filter processing order" section only makes sense to be shown when **more than one** filters are enabled. The current PR makes it so that it is shown when **at least one** filter is enabled.

Unfortunately, I don't see an easy/elegant way to achieve that with the current way that the list of available filters is built (multiple `'#type' => 'checkbox'` form elements, instead of a single `'#type' => 'checkboxes'` element). I could construct the `#states` visibility conditions so that it includes all combinations of a single ticked checkbox, but seems a really lame/massy way to go about it. The alternative would be to change the multiple `'checkbox'` elements to a single `'checkboxes'` one, but that is a considerably bigger change 🤔

**Comment by klonos** [comment]
...I would eventually like us to implement #1032, so with 99% of the problem fixed with this PR, I'm not sure that it's worth the additional effort to fix that remaining 1%.

**Comment by BWPanda** [comment]
PR works for hiding heading and weights link, but the (bottom?) border of the table is still shown...

[![Screenshot-20190902-134726-Brave.png](https://i.postimg.cc/X7V0F1dj/Screenshot-20190902-134726-Brave.png)](https://postimg.cc/w3bPYVwZ)

**Comment by klonos** [comment]
With #1032 in core since 1.16.0, the text format UI has changed to a tablesort, merging the various sections (enable/disable, sort, configure):

![image](https://user-images.githubusercontent.com/2423362/94487143-28e47280-01e9-11eb-8849-eb1610b53b0c.png)

So this is issue does not apply any longer and we can close it 🙂
