### ISSUE TITLE
Fix fieldset styling

### ISSUE THREAD

**Issue by BWPanda** [backdrop/backdrop-issues#4766]
**Description of the bug**

This started in https://github.com/backdrop/backdrop-issues/issues/3930 and was 'fixed' in https://github.com/backdrop/backdrop-issues/issues/4758. But there are still issues with the styling of fieldsets. Specifically non-collapsible ones:

![image](https://user-images.githubusercontent.com/2385329/99594300-1ba86f00-2a47-11eb-8ca1-ce9b4db5ad2f.png)

**Steps To Reproduce**

To reproduce the behavior, spin up a new site, then go to `/admin/structure/views/view/node_admin_content` and view the Pager settings.

---

PR: https://github.com/backdrop/backdrop/pull/3424

**Comment by klonos** [comment]
Meh 😓 ...thanks for raising this @BWPanda ...I'll take another stab at the fieldset styles and this time will make sure to test collapsible ones within vertical tabs.

**Comment by indigoxela** [comment]
Also meh...

It seems like the fieldset legends of _all_ fieldsets need a float, not only the collapsible ones.
At least we didn't introduce another regression, it's just that we didn't fix all of the previous ones.

**Comment by indigoxela** [comment]
Another try to fix the fieldset styles.

It still needs some tiny tweaks, but the weirdest things seem fixed.

**Comment by indigoxela** [comment]
I think, fieldset styles in Seven are fixed now.

- The gap is gone
- Nested fieldsets seem OK
- The jumping when expanding is gone

I checked following places:

- node/add/page (vertical tabs, formatting options, editor link dialog "More link options")
- admin/reports/dblog
- admin/config/people/settings
- admin/structure/views/view/node_admin_content/configure (the pager settings dialog)

But please check *everything* else, too. :wink:

**Comment by klonos** [comment]
Code looks good, but not claiming to be a CSS expert, so could use at least a second pair of 👀 

I've tested the following pages (in both RTL and LTR):

- admin/appearance/settings/basis (as both collapsible and non-collapsible fieldsets) -> 👍 
- any "HideFormatting options" fieldset under CKEditor -> 👍 
- the "Meta tags" vertical tab when editing content, which has a couple of collapsible fieldsets in it -> 👍 
- fieldsets inside block configuration modals -> 👍 
- any field/filter/sort modal in any view -> works well, but there is some "jumping" and some excessive space between fieldsets: 
![image](https://user-images.githubusercontent.com/2423362/101189823-36dac780-3660-11eb-9737-7398958510b7.png)

**Comment by klonos** [comment]
`admin/structure/views/add` seems to be still broken:

![image](https://user-images.githubusercontent.com/2423362/101191054-dcdb0180-3661-11eb-990e-17241fb4a8f0.png)

**Comment by indigoxela** [comment]
> admin/structure/views/add seems to be still broken (fieldsets w/o legends)

Right, these fieldsets have no legend. I think, we might need a different approach.

**Comment by klonos** [comment]
> I think, we might need a different approach.

Or the same approach + some additional CSS/selectors 😉

**Comment by indigoxela** [comment]
Or revert the breaking commits and start fresh. Fixing the legend overflow differently - that's what I'm currently trying.

**Comment by indigoxela** [comment]
A new [PR](https://github.com/backdrop/backdrop/pull/3424) is available for testing.

It reverts the previous two commits and fixes the legend overflow problem differently.

Note: there's still a small problem with views (too much space on top of fieldsets), but the other things are fixed - at least, that's what I think. :wink: 
Testing and feedback is welcome.

**Comment by indigoxela** [comment]
I think, I got it all working now. Please test and review.

**Comment by klonos** [comment]
We're getting really close @indigoxela, thanks for reworking this 👍 

I've installed the Metatag and Content Access modules, and tested the following again (in both RTL and LTR):

- admin/appearance/settings/basis (has both collapsible and non-collapsible fieldsets) -> 👍 
- any "Formatting options" fieldset under CKEditor -> 👍 
- the "Meta tags" vertical tab when editing content, which has a couple of collapsible fieldsets in it -> 👍 
- the "Access control" tab in content types -> 👍 
- fieldsets inside block configuration modals -> 👍 
- any field/filter/sort modal in any view -> 👍 

There are 2 regressions though:

1. You cannot anymore click anywhere inside the fieldset legend to collapse/expand - you need to click the fieldset title/link or the arrow 👎 
1. All fieldsets have a noticeable increase in hight now. See side-by-side before/after screenshots of various pages:

![image](https://user-images.githubusercontent.com/2423362/101281581-6b718f00-37d8-11eb-962b-eda1fd8ff47f.png)

![image](https://user-images.githubusercontent.com/2423362/101281605-96f47980-37d8-11eb-89b8-fd704f6765fe.png)
This one was unnecessarily tall before the change in this PR as well - perhaps we should fix it here?

![image](https://user-images.githubusercontent.com/2423362/101281648-e175f600-37d8-11eb-8e54-1121a39e1bea.png)

![image](https://user-images.githubusercontent.com/2423362/101281671-01a5b500-37d9-11eb-8d97-e6b487a1bc83.png)

![image](https://user-images.githubusercontent.com/2423362/101281698-387bcb00-37d9-11eb-8022-ff146bd0d496.png)

![image](https://user-images.githubusercontent.com/2423362/101281733-66f9a600-37d9-11eb-9d7c-2666c1b00baa.png)

**Comment by indigoxela** [comment]
> You cannot anymore click anywhere inside the fieldset legend to collapse/expand ... All fieldsets have a noticeable increase in height now

Nice catch, easy to fix (done). Ready for another round of testing.

Regarding the views fieldsets for "Create a page/block" when adding a new view - I think the size is supposed to be so. Not sure, though.

**Comment by klonos** [comment]
Fieldsets within vertical tabs seem to have their legend titles aligned slightly towards the bottom:

![image](https://user-images.githubusercontent.com/2423362/101351374-2bbeac00-3899-11eb-8324-42856dc786e2.png)

Everything else (except the "Add view" fieldsets) seems to be fixed 👍

**Comment by indigoxela** [comment]
> Fieldsets within vertical tabs seem to have their legend titles aligned slightly towards the bottom

Ooops, right, that selector was too greedy (nested fieldsets were affected).

Ready for another round of ping-pong. :stuck_out_tongue_winking_eye:

**Comment by klonos** [comment]
> Ready for another round of ping-pong. 😜

Only thing that remains to be fixed now is the spacing between fieldsets within views dialogs, which is more than the fieldsets in the rest of the admin UI. Here's for example a side-by-side screenshot of 3 collapsed fieldsets in a Views dialog, and the same in the "Access control" tab:

![image](https://user-images.githubusercontent.com/2423362/101358813-0f743c80-38a4-11eb-899f-73463bd2ff54.png)

Once that's fixed this is RTBC 👍

**Comment by indigoxela** [comment]
> Only thing that remains to be fixed now is the spacing between fieldsets within views dialogs

Your example (Access control) is actually the one that differs.

Here's a combined screenshot (Module listing page and Views field settings dialog). They fit.

![compare-gaps](https://user-images.githubusercontent.com/842066/101361927-d89c2780-389f-11eb-8278-8248954f3305.png)

**Comment by klonos** [comment]
Sure, let's leave contrib out of it. Here's a side-by-side of the Basis settings page:

![image](https://user-images.githubusercontent.com/2423362/101363721-65e47980-38aa-11eb-81d9-f0700a97f749.png)

Here's also modules list vs Basis settings page:

![image](https://user-images.githubusercontent.com/2423362/101363974-b2c85000-38aa-11eb-88e0-3906ec378442.png)

I'm starting to believe that this may be browser specific. I'm testing on Mac OS with latest Chrome.

**Comment by indigoxela** [comment]
> I'm starting to believe that this may be browser specific. I'm testing on Mac OS with latest Chrome.

Confirmed, Firefox on Linux vs. Chromium on Linux.

Chromium does not add the margins of the fieldsets with "display: table-cell", but shows the as if they were "display: block".

**Comment by indigoxela** [comment]
Comments like that make me cautious: https://github.com/backdrop/backdrop/blob/9303a9963667fdaeaae2ef6460f63eda4c40bb76/core/modules/views_ui/css/views_ui.admin.theme.css#L509

I'd prefer to not mess with that code. :wink:

**Comment by klonos** [comment]
Sure. It can always be a separate follow-up. ...looking at that inline comment though, what is the "edit option columns" that keeps being mentioned in it?

**Comment by indigoxela** [comment]
>  does anyone know what the "edit option columns" that keep being mentioned in it are?

No clue. The code is old (2011), git blame / git show didn't provide useful info.

And I'm not sure, why `display: table-cell` is set for fieldsets anyway in core/modules/system/css/system.theme.css. But that's also something that I'd prefer _not_ to touch within the scope of this issue. Although we discovered that it's buggy depending on browsers.

To my understanding this issue should really only fix the fieldset styles in Seven, and the change should be as minimal as possible.

My PR looks bigger than it actually is, BTW, the biggest part of the change is the revert of two previous commits.

Actually affected files compared to the previous state (before 1.17.2):

- core/themes/seven/css/style.css - Prevent legend overflow, alternate approach. Fix jumpy open/close animation.
- core/themes/seven/css/views-admin.seven.css - Remove obsolete workaround for views UI, which also caused jumpy animation.

This can be reviewed locally with `git diff 0124a5d7e..HEAD`, in case you have a local clone.
Or with this url on Github: https://github.com/backdrop/backdrop/pull/3424/files/0124a5d7e384600ff85cb8b140f5e0bbecdf066c..ac570314532abeee7e87e8257759cd2ab85fdd86

@klonos is it OK for you, if the additional problems / glitches we discovered while testing here get their own (follow-up) issues?

**Comment by klonos** [comment]
> To my understanding this issue should really only fix the fieldset styles in Seven, and the change should be as minimal as possible.

Agreed. We can iterate with follow-up issues to fix the remaining of the issues we found as part of this.

**Comment by BWPanda** [comment]
Requested some minor changes.

**Comment by BWPanda** [comment]
I tested the PR on my local site, and found an issue:

**Default field value: 1.17.4**
![image](https://user-images.githubusercontent.com/2385329/102687889-9632fd00-4246-11eb-9147-cad079dbedee.png)

**Default field value: PR**
![image](https://user-images.githubusercontent.com/2385329/102687901-b19e0800-4246-11eb-818e-b6c042a90ef4.png)

This same problem (lack of space under fieldset label) happens in a few other places too (e.g. Views pager settings, text filter CKEditor buttons, etc.). Basically whenever some text comes right after the label, before any form fields.

**Comment by indigoxela** [comment]
> This same problem (lack of space under fieldset label) happens in a few other places too...

In which browser? I can't reproduce this in Firefox or Chromium.

**Comment by indigoxela** [comment]
I've updated my PR with a fix for these margin inconsistencies.

Unfortunately that means, that we're back to "needs testing", as it includes a CSS code change which needs a thorough check of all the previously checked pages.
(Seven's CSS seems like a house of cards sometimes, better check one time too often, than introduce another regression...)

**Comment by jenlampton** [comment]
I've been using this patch on a site that has lots of fieldgroups, multifields, and references. It's a huge improvement over what's in core now :)

**Comment by jenlampton** [comment]
PR looks great, RTBC!

**Comment by BWPanda** [comment]
Thanks @indigoxela, @klonos & @jenlampton! I've merged https://github.com/backdrop/backdrop/pull/3424 into 1.x and 1.17.x.
