### ISSUE TITLE
Modify `.htaccess` to allow backdrop to serve `.well-known` URIs

### ISSUE THREAD

**Issue by danieljrmay** [backdrop/backdrop-issues#5583]
## Description of the need

I have recently started to use Backdrop, and as my first development task I ported my `Security.txt` module from [Drupal](https://www.drupal.org/project/securitytxt "Security.txt Drupal module") to [Backdrop](https://github.com/danieljrmay/securitytxt  "Security.txt Backdrop module"). This module serves a two _well-known_ URLs:

- `/.well-known/security.txt`
- `/.well-known/security.txt.sig`

This works with Drupal 7 & 9 as their `.htaccess` files do not deny access to files (and therefore Drupal paths) beginning with `.well-known`. However, Backdrop's `.htaccess` file (as of version 1.21.4) blocks all files (and therefore Backdrop paths) beginning with `.` without an exemption for those beginning with `.well-known`.

There are a number of standardized [well-known URIs](https://en.wikipedia.org/wiki/Well-known_URI) which it would be good to allow Backdrop to serve, indeed I have started work on [a general module to do this](https://github.com/danieljrmay/well_known_uris). However, the current Backdrop `.htaccess` file prevents these modules from working without the user manually patching their `.htaccess` file or creating a `.well-known` directory in their document root.

## Proposed solution

Modify the Backdrop `.htaccess` file. 

I will submit a PR with my proposed change shortly.

## Alternatives that have been considered

- Any module which wishes to serve a _well-known URI_ should add a line to the "Status Report" informing the user that they must manually create a `.well-known` directory in their document root. This may not be easy or indeed possible depending on a user's technical expertise or hosting arrangements.

## Draft of feature description for Press Release (1 paragraph at most)

If this issue is resolved and the two mentioned modules are approved then we could have something like:

- Backdrop now includes support for the [Security.txt standard](https://securitytxt.org/) via the `security.txt` module.
- Backdrop now includes support for the [change-password service](https://w3c.github.io/webappsec-change-password-url) via the `well_known_uris` module.

**Comment by danieljrmay** [comment]
Hi @indigoxela 

> One request: can you add the link to this issue in your PR description?

Done

**Comment by indigoxela** [comment]
> Done

Hm, I still can't see it: https://github.com/backdrop/backdrop/pull/4045 ... another try?

**Comment by danieljrmay** [comment]
> Hm, I still can't see it: [backdrop/backdrop#4045](https://github.com/backdrop/backdrop/pull/4045) ... another try?

Whoops, yes that should be done now. 😉

**Comment by indigoxela** [comment]
> The issue comes when you try to get Backdrop to serve a .well-known/SERVICE URL...

So it's not about actual files, but about "virtual" ones (provided via code)? But wait, that also works for me. :thinking:

A super-silly tiny module:

```
<?php

function foobar_menu() {
  $items = array();
  $items['.well-known/foobar'] = array(
    'page callback' => 'foobar_view',
    'access callback' => TRUE,
    'delivery callback' => 'backdrop_json_deliver',
  );
  return $items;
}

function foobar_view() {
  return array('hello' => 'world');
}
```
Enable module, open url `/.well-known/foobar` - and I get my json.

What am I missing?

**Comment by danieljrmay** [comment]
> So it's not about actual files, but about "virtual" ones (provided via code)? But wait, that also works for me. thinking
> 
> A super-silly tiny module:
> 
> ```
> <?php
> 
> function foobar_menu() {
>   $items = array();
>   $items['.well-known/foobar'] = array(
>     'page callback' => 'foobar_view',
>     'access callback' => TRUE,
>     'delivery callback' => 'backdrop_json_deliver',
>   );
>   return $items;
> }
> 
> function foobar_view() {
>   return array('hello' => 'world');
> }
> ```
> 
> Enable module, open url `/.well-known/foobar` - and I get my json.
> 
> What am I missing?

If you have a `DOCUMENT_ROOT/.well-known` directory on your filesystem then I would expect that to work. If you don't, then I may have got very confused! I will try your `foobar` module and report back…

**Comment by indigoxela** [comment]
> If you have a DOCUMENT_ROOT/.well-known directory on your filesystem then I would expect that to work. If you don't, then I may have got very confused!

I don't - no such directory. :wink:

**Comment by danieljrmay** [comment]
So this is interesting. I have just tried your `foobar` module and it does not work for me. :confused: 

Steps:

1. Create a new container for Backdrop 1.21.4 based on Fedora 35 with PHP 8.0.17, Apache 2.4.53, MariaDB 10.5.13, PHP-FPM.
2. On my host computer use Firefox to go to `http://localhost:8080` which redirects to Backdrop's install page. Complete the installation in the normal way.
3. Go to `http://localhost:8080/admin/reports/status` and everything looks good — all green ticks.
4. Go to `http://localhost:8080/admin/modules/list` and enable your `Foobar` module.
5. Go to `http://localhost:8080/.well-known/foobar` and get a 403 Forbidden page from apache (not the backdrop page). Here is the line from my apache access log: `10.0.2.100 - - [12/Apr/2022:07:29:29 +0000] "GET /.well-known/foobar HTTP/1.1" 403 199 "-" "Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:99.0) Gecko/20100101 Firefox/99.0"`. The corresponding line from my apache error log is: `[Tue Apr 12 07:29:29.702786 2022] [authz_core:error] [pid 84:tid 224] [client 10.0.2.100:37996] AH01630: client denied by server configuration: /var/www/html/.well-known`. 
6. Create a well-known directory on the filesystem of my container with `mkdir /var/www/html/.well-known`.
7. Reload the browser at `http://localhost:8080/.well-known/foobar` and it works. Apache access log `10.0.2.100 - - [12/Apr/2022:07:35:05 +0000] "GET /.well-known/foobar HTTP/1.1" 200 17 "-" "Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:99.0) Gecko/20100101 Firefox/99.0"`.
8. Remove the well-known directory with `rm -rf /var/www/html/.well-known`.
9. Reload the browser at `http://localhost:8080/.well-known/foobar` and we are back to an Apache provided 403 Forbidden page.
10. Copy the modified `.htaccess` into place `cp modules/custom/securitytxt/htaccess/modified.htaccess .htaccess` and restart apache with `systemctl restart httpd.service`.
11. Reload the browser at `http://localhost:8080/.well-known/foobar` and it works!

What installation stack were you using when it worked for you?

**Comment by indigoxela** [comment]
> What installation stack were you using when it worked for you?

That's an actual webserver, Apache, php-fpm, with a subdomain pointing to that vhost. No container, not on localhost.

Hm... localhost might be the culprit for you.

**Comment by indigoxela** [comment]
> What version of Apache are you using?

Server version: Apache/2.4.53 (Debian)

Nothing special in the vhost file, but maybe that's relevant:

```
  <Directory /var/www/.../...>
    AllowOverride All
  </Directory>
```

**Comment by danieljrmay** [comment]
Does **not** work for me in a Debian 11 virtual machine with: Backdrop
1.21.4, PHP 7.4.28, Apache 2.4.53! :confused:

```apache
# /etc/apache2/sites-enabled/000-default.conf

<VirtualHost *:80>
    ServerName backdrop.local
    ServerAdmin webmaster@localhost
    DocumentRoot /var/www/html

    ErrorLog ${APACHE_LOG_DIR}/error.log
    CustomLog ${APACHE_LOG_DIR}/access.log combined

    <Directory /var/www/html>
        AllowOverride All
    </Directory>
</VirtualHost>

# vim: syntax=apache ts=4 sw=4 sts=4 sr noet
```

```
> cat /etc/hosts

127.0.0.1    localhost

# The following lines are desirable for IPv6 capable hosts
::1     localhost ip6-localhost ip6-loopback
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters

127.0.0.1    backdrop.local
```

```
> apache2ctl -t -D DUMP_MODULES
Loaded Modules:
 core_module (static)
 so_module (static)
 watchdog_module (static)
 http_module (static)
 log_config_module (static)
 logio_module (static)
 version_module (static)
 unixd_module (static)
 access_compat_module (shared)
 alias_module (shared)
 auth_basic_module (shared)
 authn_core_module (shared)
 authn_file_module (shared)
 authz_core_module (shared)
 authz_host_module (shared)
 authz_user_module (shared)
 autoindex_module (shared)
 deflate_module (shared)
 dir_module (shared)
 env_module (shared)
 filter_module (shared)
 mime_module (shared)
 mpm_prefork_module (shared)
 negotiation_module (shared)
 php7_module (shared)
 reqtimeout_module (shared)
 rewrite_module (shared)
 setenvif_module (shared)
 status_module (shared)
 ```

Added the following line to `/var/www/html/settings.php` so that the
status report shows all green ticks.

```php
$settings['trusted_host_patterns'] = array('^backdrop\.local$');
```


After enabling your `foobar` module and going to
`http://backdrop.local/.well-known/foobar` I get the same apache 403
forbidden page. Here is the relvent line from the apache access log:

```
127.0.0.1 - - [12/Apr/2022:11:41:28 +0100] "GET /.well-known/foobar HTTP/1.1" 403 496 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:91.0) Gecko/20100101 Firefox/91.0"
```

Corresponding line in apache error log:

```
[Tue Apr 12 11:41:28.275298 2022] [authz_core:error] [pid 3679] [client 127.0.0.1:55236] AH01630: client denied by server configuration: /var/www/html/.well-known
```

@indigoxela would you be able to help save my sanity by confirming that your installation is denying access to dot files e.g. when you point your browser at `http://FQDN/.gitignore` (or any other dot file in your document root) you get a 403 forbidden page provided by apache?

**Comment by indigoxela** [comment]
> Does not work for me in a Debian 11 virtual machine

Crazy!

> ... your installation is denying access to dot files e.g. when you point your browser at http://FQDN/.gitignore

I get an Apache Forbidden - as expected: `... "GET /.gitignore HTTP/1.1" 403 ...`

**Comment by danieljrmay** [comment]
> Crazy!

Yes! :confused: 

Surely there must be a difference between our Apache versions/configurations because that is what is what is denying me access to `http://FQDN/.well-known/foobar`?

Would you be able to share the output of `apache2ctl -t -D DUMP_MODULES`?

Also can we confirm that we both have exactly the same `.htaccess` file? Here's mine:

```
> md5sum .htaccess 
2617ec85bbe985d7e385c762cd78466a  .htaccess
```

**Comment by indigoxela** [comment]
> Surely there must be a difference between our Apache versions/configurations

I agree, but it's still very odd.

```
md5sum .htaccess
2617ec85bbe985d7e385c762cd78466a  .htaccess
```
That's the same.

```
# apachectl -M
Loaded Modules:
 core_module (static)
 so_module (static)
 watchdog_module (static)
 http_module (static)
 log_config_module (static)
 logio_module (static)
 version_module (static)
 unixd_module (static)
 access_compat_module (shared)
 alias_module (shared)
 auth_basic_module (shared)
 auth_digest_module (shared)
 authn_core_module (shared)
 authn_file_module (shared)
 authz_core_module (shared)
 authz_host_module (shared)
 authz_user_module (shared)
 autoindex_module (shared)
 cgi_module (shared)
 dav_module (shared)
 dav_fs_module (shared)
 deflate_module (shared)
 dir_module (shared)
 env_module (shared)
 fcgid_module (shared)
 filter_module (shared)
 headers_module (shared)
 mime_module (shared)
 mpm_prefork_module (shared)
 negotiation_module (shared)
 proxy_module (shared)
 proxy_fcgi_module (shared)
 reqtimeout_module (shared)
 rewrite_module (shared)
 setenvif_module (shared)
 socache_shmcb_module (shared)
 ssl_module (shared)
 status_module (shared)
```
fcgi, not mod_php, but that really shouldn't matter. Public IP, not localhost, but why would that make any difference here?

**Comment by danieljrmay** [comment]
> fcgi, not mod_php, but that really shouldn't matter. Public IP, not localhost, but why would that make any difference here?

What other relevant differences do we have? 

- Presumably you are accessing your site via HTTPS as opposed to my HTTP.
- Some difference hiding in our `/etc/apache2/**/*.conf` files?

Thank you so much for your help with this! I will try and set up `fcgi` in my virtual machine and report back…

**Comment by indigoxela** [comment]
Found it! The difference is a `<Location />... ` directive in the vhost file (I use that to close dev webs and toggle them to open, when it comes to presentation).

If I completely comment that out, my Apache behaves like your Apache. Phhhhew - logic has us back. :wink:

This means, I can test your PR - and I did. And it works for me. :+1:

**Comment by danieljrmay** [comment]
> Found it! The difference is a `<Location />... ` directive in the vhost file (I use that to close dev webs and toggle them to open, when it comes to presentation).

Oh wow! Thank you! :1st_place_medal: 

I was about to report that it wasn't FPM/FastCGI because I installed that and it didn't work. You have saved me from having to try the *really crazy* stuff! :grinning:

**Comment by indigoxela** [comment]
Oh, one last request... It seems like our test runners welcome new contributors with a random test failure. (Witchcraft...)

A completely unrelated test failed, so you should:

1. Close your PR
2. Wait a minute
3. Re-open your PR

I'm sure this time all functional tests pass.

**Comment by danieljrmay** [comment]
@indigoxela Done, and thank you so much for all your help! :smile:

**Comment by herbdool** [comment]
Thanks @danieljrmay and @indigoxela for figuring this out. The code looks good. I've set the milestone to 1.21.5 since it would be good for the 1.21.* release as well. Though I can't recall if a change to .htaccess needs to be in a major release. @quicksketch would know better.

**Comment by quicksketch** [comment]
Modifying `.htaccess` is okay for bug fix releases (when fixing bugs). We have another `.htaccess` change already in the next release (https://github.com/backdrop/backdrop-issues/issues/3903) so this is a great time to include this fix as well.

**Comment by quicksketch** [comment]
I merged https://github.com/backdrop/backdrop/pull/4045 into 1.x and 1.21.x. Thank you and welcome @danieljrmay!

Thanks @indigoxela, @herbdool, and @laryn for reviewing and getting Daniel on-boarded!
