### ISSUE TITLE
admin/config/administration/admin_bar -> fatal error

### ISSUE THREAD

**Issue by Lowell20** [backdrop/backdrop-issues#591]
Fatal error: Call to undefined function admin_bar_settings_process_components() in .../core/includes/form.inc on line 1859

git tag v1.0.0

**Comment by kreynen** [comment]
I am getting this error as well on a clean 1.0 install.

**Comment by kreynen** [comment]
Looking at https://github.com/backdrop/backdrop/blob/1.x/core/modules/admin_bar/admin_bar.info vs. https://github.com/backdrop/backdrop/blob/1.x/core/modules/admin_bar/admin_bar.module#L20.  Path should be using - instead of _, right?  I belive admin/config/administration/admin-bar is correct.  Working on a PR to fix this, but I'd like to confirm that.

**Comment by Lowell20** [comment]
Nice catch on the admin_bar menu link. It is hard to tell convention of _ or -. I have found both examples in project. Also, this is separate issue, does not solve fatal error. There is some new code added at the last minute that, when commented out at line 1859, does prevent fatal error. But we don't know what they were doing with code, maybe just a typo in function name? In any case, after morning coffee I am sure they will resolve immediately.

**Comment by quicksketch** [comment]
Doh, I thought that particular line had been deleted. We just need to delete lines 688-690 in admin_bar.inc.

Separately, I also think that `admin_bar` should probably be `admin-bar` in the URL.

**Comment by quicksketch** [comment]
This should fix both the fatal and the path:

https://github.com/backdrop/backdrop/pull/683

**Comment by kreynen** [comment]
That fixed the issues for me.  I didn't mean to imply that the inconsistent path was the cause of the error.  It was just a mistake a saw when getting to the error. 

Is there documentation about the preferred process for updating the status of issues in backdrop-issues? Do you close these when the PR for the fix is merged to dev or leave them open until the fix is in a tagged release?

**Comment by quicksketch** [comment]
> Is there documentation about the preferred process for updating the status of issues in backdrop-issues? 

Hm, not yet. We could build it into the pages for https://backdropcms.org/develop/code and https://backdropcms.org/develop/pull-requests.

> Do you close these when the PR for the fix is merged to dev or leave them open until the fix is in a tagged release?

The issue is closed as soon as it is fixed in Git, and we assign it the next milestone so we can see what's going to be in the next release.

**Comment by jackfoust** [comment]
Just as an FYI this is still an issue with a clean Pantheon Backdrop install. I had to add the Github repo as an upstream and merge to proceed.

**Comment by quicksketch** [comment]
> I had to add the Github repo as an upstream and merge to proceed.

We'll probably leave the Pantheon repo on official releases only. Although this is (so far) our most visible bug in 1.0.0, we'd like to wait to see if anything else critical shows itself in the next couple of days. We'll make a 1.0.1 release next week, and update Pantheon's repo to match.

**Comment by jackfoust** [comment]
I can see that. My only concern was someone spinning up a Pantheon instance from the Backdrop home page and then receiving an error from the first item they see in the configuration drop down.

**Comment by quicksketch** [comment]
Yeah, understandable. We need to establish if we should optimize the experience for Pantheon when possible. @jenlampton and @populist, you guys have a preference here?

**Comment by jenlampton** [comment]
In this case, I'd like to see the fix go up as soon as possible. Apparently that never-used admin form is more visible when testing than I'd imagined! :)

**Comment by quicksketch** [comment]
Okay then. I agree that practicality (and press) is more important than policy at the moment. Updated the backdrop-pantheon repository to reflect the latest changes. Thanks @jackfoust!
