### ISSUE TITLE
Exposed group filter for date not working

### ISSUE THREAD

**Issue by andyjeanne** [backdrop/backdrop-issues#6976]
There are a couple of problems.  I have a date field (single, no start/end) and would like to filter a list in a View to show items with the date in the past, those in the future, and a list of all.  I'd like to do this with a grouped exposed filter so users can toggle between the three options , while still being able to use combinations of other available filters.  

The first issue is that on the Views editing interface, when I select it to be exposed and a grouped filter, I get the option to select a type (relative or date) but then do not see another field where I can enter the date or relative criteria:

<img width="1949" height="603" alt="Image" src="https://github.com/user-attachments/assets/cbaa5bf6-364d-411f-bb98-1551abe23b4c" />

I am migrating a site from Drupal 7 and I do remember a similar issue happening before (although it has been 6 years ago so a little fuzzy on details).  I did use one of the provided patches from the issue queue.  Here is the discussion in the Drupal docs:

https://www.drupal.org/project/views/issues/1764902

I don't think any of the patches cleared testing and wouldn't work directly with the current Backdrop code but might be a helpful reference.  

Note that if I do a single filter, without grouping, just selecting to show things in the future, it works fine.  I thought I might use that as a reference and try manually editing the config file for the View after switching it to grouped.  The info for the single file is:

"operator": ">",
                        "value": {
                            "min": null,
                            "max": null,
                            "value": null,
                            "type": "date"
                        },

But trying to set that manually for a grouped item did not get it to work; it always just showed all the values.  Also not sure why they are all null, instead of one indicating "now"?  I tried copying the array values from the Views export from the Drupal site and that did not work either.  So I think there are other problems beyond not being to set the values in the editing interface.  If you refer to the Drupal issue queue, many folks describe the same problems, beyond not just being able to enter values in the front end. 

I'm on the current version of Backdrop, PHP 7.4 (about to upgrade once this Drupal site is shut down), MySQL, Ubuntu 20.04.6, and have tested in Firefox and Chrome.  

Any help or suggestions you can provide would be appreciated.  I have some sort of clunky workarounds I can do if it comes to that but would really like to be able to keep this setup.

**Comment by olafgrabienski** [comment]
Hi @andyjeanne, thanks for reporting this issue. I'm not an expert in grouped exposed filters, but I was curious and added such a filter to one of my test sites. To get a quick result, I filtered by the "Updated" date and provided two options: _Last years_ vs. _This year_.

This grouped filter works, and I do see the fields to enter a date or an offset (see screenshot below), so generally it seems to work fine. Can you check if the example works on your site as well?

Another question: You mentioned a migration from Drupal 7. Is this a site which was _upgraded_ from D7, or are you rebuilding the site from scratch?

**Screenshot:**

<img width="1062" alt="Image" src="https://github.com/user-attachments/assets/9cf74a43-6401-41db-b47a-8f96c09f1fd6" />

**Comment by jenlampton** [comment]
I ran into this issue this week also. My set up is similar, but not exaclty the same as @andyjeanne, but I have the same desired result. 

It only coms up when you have the setting `Filter type to expose` set to `Grouped filters ` (I did not see this setting for you @olafgrabienski, and also wonder if you might be using a different type of date, like published or updated?

<img width="530" height="124" alt="Image" src="https://github.com/user-attachments/assets/1ebacbe5-200d-427a-8216-14aeb8bb6c79" />

My "Value" column shows me a select containing options for how I would like to set the value. And the two fields for setting the value, "Select a date" and "Relative date" are set to `display:none`.  (Below is what the area looks like after I have manually disbaled the `display:none.` )

<img width="730" height="217" alt="Image" src="https://github.com/user-attachments/assets/a9ab63bc-ea36-435c-9ba1-0434ed97e68d" />

As soon as I select an option in the  "Select a date" select list, one of the two other fields is supposed to be shown. But it does not appear. 

<img width="1333" height="337" alt="Image" src="https://github.com/user-attachments/assets/29ba7171-d31c-4076-812b-5ed9dddfd743" />

This does work as expected when Switching from "Grouped filters" back to "Single filter":

<img width="829" height="194" alt="Image" src="https://github.com/user-attachments/assets/dd8f04d7-46bb-467b-9986-620f888cc814" />

But the switch from "Grouped filters" back to "Single filter" results in PHP errors:

```
    Warning: Undefined array key "operator" in date_views_filter_handler_simple->value_validate() (line 465 of /var/www/html/web/core/modules/date/views/date_views_filter_handler_simple.inc).
    Warning: Undefined array key "operator" in date_views_filter_handler_simple->value_validate() (line 465 of /var/www/html/web/core/modules/date/views/date_views_filter_handler_simple.inc).
    Warning: Undefined array key "operator" in date_views_filter_handler_simple->value_validate() (line 495 of /var/www/html/web/core/modules/date/views/date_views_filter_handler_simple.inc).
    Warning: Undefined array key "value" in date_views_filter_handler_simple->value_validate() (line 513 of /var/www/html/web/core/modules/date/views/date_views_filter_handler_simple.inc).
    Warning: Trying to access array offset on null in date_views_filter_handler_simple->value_validate() (line 513 of /var/www/html/web/core/modules/date/views/date_views_filter_handler_simple.inc).
    Warning: Trying to access array offset on null in date_views_filter_handler_simple->value_validate() (line 513 of /var/www/html/web/core/modules/date/views/date_views_filter_handler_simple.inc).
    Warning: Undefined array key "min_group" in date_views_filter_handler_simple->value_validate() (line 513 of /var/www/html/web/core/modules/date/views/date_views_filter_handler_simple.inc).
    Warning: Trying to access array offset on null in date_views_filter_handler_simple->value_validate() (line 513 of /var/www/html/web/core/modules/date/views/date_views_filter_handler_simple.inc).
    Warning: Undefined array key "max_group" in date_views_filter_handler_simple->value_validate() (line 513 of /var/www/html/web/core/modules/date/views/date_views_filter_handler_simple.inc).
    Warning: Trying to access array offset on null in date_views_filter_handler_simple->value_validate() (line 513 of /var/www/html/web/core/modules/date/views/date_views_filter_handler_simple.inc).
```

I tested un-hidinfg the fields manually and entering the values I wanted to see if it was just a javascript problem, but the values also do not save, matching @andyjeanne's experience. 

I suspect the form API structure of this page changes significantly when switching "Single filter" to "Grouped filters", and that breaks both the javascript that works for "Single filter" and also the submit handler, causing these values not to save properly.

**Comment by argiepiano** [comment]
FWIW, the views filter handler for entity date properties such as node's `changed` or `scheduled` (handler: `views_handler_filter_date`) is different from the Field API date fields filter handler (handler: `date_views_filter_handler`). So the issue must be in the latter filter.

**Comment by argiepiano** [comment]
PR https://github.com/backdrop/backdrop/pull/5176 provided.

@andyjeanne, @jenlampton, could you test? I adapted the Drupal 7 patch that was never merged. There are some differences in the file (my guess is that Backdrop's core date module has not kept up to date with D7's date project). In my limited testing, this worked.

Test failure seems random and not related to this PR.

**Comment by olafgrabienski** [comment]
> I did not see [the Grouped filters] setting for you, and also wonder if you might be using a different type of date, like published or updated?

Yes, I used the "Updated" date, that might explain our different results, see also https://github.com/backdrop/backdrop-issues/issues/6976#issuecomment-3678873150.

**Comment by indigoxela** [comment]
> Test failure seems random and not related to this PR.

Yes, that one's unrelated. But the phpcs nagging's related @argiepiano 😉 
Easy to fix, though (space / indentation...).

**Comment by argiepiano** [comment]
@indigoxela thanks. The test used to tell us which lines - but not anymore. Is there a way to find out where the space/indentation problem are?

**Comment by indigoxela** [comment]
> The test used to tell us which lines - but not anymore...

Where the annotation is (which also lists the line):

<img width="915" height="233" alt="Image" src="https://github.com/user-attachments/assets/63313362-1292-4126-bad9-c547111b916f" />

**Comment by argiepiano** [comment]
OK, fixed the standards issues. Ready for review and testing.

**Comment by jenlampton** [comment]
I'm testing this and it seems to have broken the ability to save a normal (not exposed, not grouped) date filter. 

<img width="1345" height="308" alt="Image" src="https://github.com/user-attachments/assets/a8715751-9259-4bec-84fd-76cfb1848c2d" />

I can enter a relative value here, but it will not save. 

Removing the patch fixes the issue.

**Comment by argiepiano** [comment]
> I can enter a relative value here, but it will not save.

Thanks for catching that. I'll check what's going on.

**Comment by argiepiano** [comment]
I had a quick look at the patch - leaving this note here for future me or anyone who wants to take over. The issue of why this is not saving when not exposed is the positioning of the submitted values in the `$form state['values']`, which is the result of the $form array, which differs (I think) from the older method. Look specifically at `date_views_filter_handler_simple::value_form()` and `date_views_filter_handler_simple::date_parts_form()`. 

I'll come back to this.

**Comment by jenlampton** [comment]
I wonder if there's a way we can use `#parents` or `#tree = FALSE` to assure the values in $form_state are the same, regardless of what happens in $form?

**Comment by shivansunfire** [comment]
Without any patch, this is not exactly that Single works and Group doesn't, but when you just click on the radio button group, even without changing from one to another (Single / Group), the UI just change into the table mode or the other, and in the table mode it doesn't show the fields (they are with display:none as @jenlampton said).

https://github.com/user-attachments/assets/67ca1c20-ca10-46e1-8b7a-852857f2ba92

**Comment by shivansunfire** [comment]
Also, without the patch, I see that, despite the Single exposed filter allows me as a site builder to choose "Enter a relative date" and write that Relative date, then the view acts like what's chosen is the "Select a date" option, and that's what it shows in the view summary on Filter Criteria section.

**Comment by argiepiano** [comment]
The patch was adapted from D7. It took a while to adapt, but the functionality has diverged substantially from D7. I likely won't be able to go back to this until the end of clases (May), so if someone wants to offer an alternative patch that'd be great.

**Comment by shivansunfire** [comment]
Already working on it 👍

**Comment by shivansunfire** [comment]
Re-rolled patch https://patch-diff.githubusercontent.com/raw/backdrop/backdrop/pull/5176.diff which didn't apply:
[5176-260310.patch](https://github.com/user-attachments/files/25865983/5176-260310.patch)

**Comment by shivansunfire** [comment]
I think I fixed this, here is the PR: https://github.com/backdrop/backdrop/pull/5227. The only test failure looks like non-related.

**Comment by herbdool** [comment]
Thanks @juanolalla I'll test this tomorrow

**Comment by herbdool** [comment]
The PR works well for me. There's still an issue with the `#states` in grouped options and dependency on the operator. Specifically, if `is between` is chosen then only the Start and End date should be visible. And likewise if `is equal to` is chosen then Stard/End date fields should be hidden.

<img width="1547" height="331" alt="Image" src="https://github.com/user-attachments/assets/d4f7eb86-39dc-4b6c-94ec-6fff7f07f81c" />

This doesn't hurt the functionality but could be confusing.

**Comment by herbdool** [comment]
@juanolalla I made one small code suggestion in the PR. https://github.com/backdrop/backdrop/pull/5227/changes#r3236038288

**Comment by herbdool** [comment]
Thanks @juanolalla. It looks ready to merge.

**Comment by quicksketch** [comment]
With the amount of chaos around the release and b.org outages today I don't think I can review this for 1.33.3. We'll get it into the next bugfix release (1.34.1). Thank you @juanolalla and @herbdool!

**Comment by laryn** [comment]
Thank you to @andyjeanne for filing the issue, and to @argiepiano and @juanolalla (and all the people involved in [the D7 issue](https://www.drupal.org/project/date/issues/1876168)) for the fix. Thanks to @herbdool for the code review and to @jenlampton, @olafgrabienski, and @indigoxela for testing. I gave it a final test walkthrough on the sandbox and it looks great. I merged it into 1.x and 1.34.x.

**Comment by laryn** [comment]
Reopening after reverting this commit. See https://github.com/backdrop/backdrop-issues/issues/7154

Apparently we'll need expanded test coverage to ensure that various types of date-related views are working, along with whatever fixes are needed in the code.
