### ISSUE TITLE
Re#736 - Tabs (Primary and Secondary Tabs)

### ISSUE THREAD

**Issue by wesruv** [backdrop/backdrop-issues#737]
See master issue for instructions/guidelines for implementation: 
https://github.com/backdrop/backdrop-issues/issues/736

![style guide backdrop](https://cloud.githubusercontent.com/assets/5607236/6276177/e7a7daf4-b852-11e4-93fa-b6b93a279dcb.png)

**Comment by wesruv** [comment]
PR at: https://github.com/backdrop/backdrop/pull/757
Going to do some more testing before I throw this at someone, but it's a good start and may be good to go.
@jenlampton or @quicksketch what browsers are we supporting/what do I test in?

**Comment by quicksketch** [comment]
Awesome!

> what browsers are we supporting/what do I test in?

We support IE8 and up in Backdrop 1.x.

**Comment by quicksketch** [comment]
A couple of issues in the current PR.

There's a 1px hairline below the primary tabs in Seven:

![hairline](https://cloud.githubusercontent.com/assets/100206/6634211/dc16ab32-c911-11e4-8111-7eab9895a052.png)

The front-end theme Bartik seems to have been affected by these changes:

![front-end-tabs](https://cloud.githubusercontent.com/assets/100206/6634213/e53f8b34-c911-11e4-9fa9-271999118e5f.png)

**Comment by quicksketch** [comment]
This PR still needs some work. I tried it with the font changes and we still have the hairline between the tabs and the main body area.

**Comment by wesruv** [comment]
Yeah, sorry I'm going to get in the fixes for all of my PR's on the new branch tomorrow.

**Comment by wesruv** [comment]
@quicksketch the reason there's a gap is because the font size on the body isn't set to 16px on the `body` element like it is in the styleguide. I thought I had gotten that in, but now I must have been dreaming.

How should I add that bit in? It's fundamental to all our styling tickets since it's on the `body` tag.

**Comment by wesruv** [comment]
New PR against `1.x-new-style` here: https://github.com/backdrop/backdrop/pull/795

**Comment by quicksketch** [comment]
> How should I add that bit in? It's fundamental to all our styling tickets since it's on the body tag.

If you can file an independent PR against https://github.com/backdrop/backdrop-issues/issues/738 to correct the font size?

**Comment by quicksketch** [comment]
Thanks @wesruv! I merged in the new PR to adjust the font size, but the hair-line is still there. Could you take another look?

**Comment by wesruv** [comment]
@quicksketch I think that should do it: https://github.com/backdrop/backdrop/pull/795
![style guide l backdropdev com](https://cloud.githubusercontent.com/assets/5607236/6860402/30a16b46-d3fe-11e4-9877-1c5f35b177b5.png)
I had to do a `git pull --rebase` once that was merged into `1.x-new-style`. If not let me know what Browser/OS you're using and I'll take a look.

**Comment by quicksketch** [comment]
Hi @wesruv, you probably hate hearing this, but it works fine in Chrome but still has the hair-line in Firefox on OSX.

I also noticed that the active tab background color is different than the page background. This can have an incorrect appearance when there are no secondary tabs. Do you think we could put the `#FAFAFA` background on the page as well as part of this PR? It seems like it's appropriate to match the tabs.

**Comment by wesruv** [comment]
@quicksketch 
I've learned to live with it :P
I couldn't replicate it even in BrowserStack. Very strange, BUT I think I fixed it. Give it one more shot, I extended the tabs underneath the secondary tabs a few pixels.

**Comment by quicksketch** [comment]
Hey @wesruv, I'm still seeing the tiny hairline. In my testing, I could correct it by increasing the height of the `ul.primary` selector from `2.534em` to `2.58em`. The `ul` just isn't quite tall enough and leaves the tiny line beneath it due to the `overflow: hidden` of its content. I imagine that height number was calculated in some way and my adjustment is a crude work-around. Does that help narrow it down?

My system where I'm seeing this:

Mac OS X 10.10.1
Firefox 36.0.4

**Comment by wesruv** [comment]
Aha! I can reproduce it in Browserstack with those specs. Danke! I'll let you know when I have a fix.

**Comment by quicksketch** [comment]
Hi @wesruv, I've been working on th1.x-new-style branch today and I realized that the 1px hairline is there *even without this PR*. So it's an existing issue that was probably introduced after our font changes. Would you be fine with me just merging this as-is and then we can take a look at the hairline problem in a separate issue?

**Comment by jenlampton** [comment]
I agree that we should call this good and merge it as is. Better is the enemy of done!

**Comment by quicksketch** [comment]
Okay, merged in https://github.com/backdrop/backdrop/pull/795. I'll file a new issue for the hairline problem that still persists. I filed a new followup at https://github.com/backdrop/backdrop-issues/issues/877.
