### ISSUE TITLE
Make sure the token browser modal is centered on screen.

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#916]
Screenshot:

![token_browser_modal_not_centered](https://cloud.githubusercontent.com/assets/2423362/7552974/fa70b54e-f717-11e4-9e2a-ac0d76743e16.png)

**Comment by quicksketch** [comment]
Yikes! Well this might be inadvertently fixed by #894.

What browser are you using so I can reproduce?

**Comment by quicksketch** [comment]
I tried this in Chrome and Firefox but I couldn't reproduce. I noticed that it looks like you have the new styleguide images (the error icon is white) but the CSS on the page is still the old Seven theme. This may simply be a stale CSS problem? In which case, a cache clear or running update.php may solve the problem, which will iterate the query string on CSS files.

**Comment by klonos** [comment]
It's on Firefox 40.0a1 latest x64 nightly. The second time I visited the page, the last position of the dialog was remembered. Still not centered, but at least where I last moved it and thus within view. Clear caches was the first thing I did before I filed this issue.

**Comment by klonos** [comment]
...not sure about the images. I compared directories between what I have and 87/pathauto and merged files but the ```message-32-*.png``` and ```message-*.svg``` under ```/core/misc``` are missing from the 87/pathauto, so I did not touch them.

**Comment by klonos** [comment]
...yep, that was it. Anyways, I think that the images thing is irrelevant to the reported issue.

**Comment by klonos** [comment]
Can't reproduce now either. Lets close it and I'll re-open if I manage to reproduce again.
